#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język niemiecki: Karolina Franieczek
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#                   _   _      _      __  ___   _ _____ _____
#                  | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#                  |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#                  | |\  |  __/ |_  __//  \| |_    / /  ___) |
#                  |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#                   __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#                  / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#                 | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#                  \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#                  |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#tłumaczenia
 
 
#########################################################################################################################################################################
#tlumaczenia_apm
export TEXT_APM1="Tu as installé le script d'APM en version vieux ou en version incomplet, installe la dernière version.\nDans cet moment l'installation du script d'APM va se commencer.\n\nVeux-tu installer? "
export TEXT_AKTUALNY_PROFIL_APM="Le profil actuel d'APM"
export TEXT_ZMIEN_PROFIL_APM="Changes le profil APM à:"
export TEXT_APM2="Pour changer le statut d'APM installe la dernière version"
export TEXT_WERSJA_APM="version installée d'APM"

#########################################################################################################################################################################
#tlumaczenia_backuprepo
export a1="Crée la sauvegarde des dépôts et des clés GPG"
export a2="Restaure des dépôts du fichier de la sauvegarde"
export a3="Télécharge des clés GPG manquant"
export a4="Répare des signatures GPG erronées"
export a5="Supprime des clés GPG inutiles"
export a6="Ajouter ou supprimer des applications / pilotes et dépôts"
export a7="Installez des logiciels"
export a8="éditeur d'installation"
export MENU1="Acitve le dépôt des partenaires de Canonical"
export MENU2="Désactive le dépôt des partenaires de Canonical"
export MENU_OPIS="Modifier la liste des paquets:"
export TEXT_BACKUP1="Un ensemble des scripts concernant des clés GPG et des dépôts."
export TEXT_BACKUP2="Montre le fichier source.list.backup"
export TEXT_BACKUP3="Dans cet moment la substitution des dépôts va succéder"
export TEXT_BACKUP4="Tu as succédé des fichiers des dépôts."
export TEXT_BACKUP5="Tu as arrêté le procès de substitution des dépôts."
export TEXT_BACKUP6="Tu as montré le fichier erroné!"
export TEXT_BACKUP7="La création du fichier: source.list.backup\n"
export TEXT_INSTALACJA="\n\nPRÊT !!! - presse enter"
export TEXT_KLUCZ="la clé GPG"
export TEXT_DOSTAWCA_KLUCZA="le fournisseur du clé"
export TEXT_ZAZNACZ_KLUCZE="Marque les clés GPG, lesquels veux-tu supprimer:"
export TEXT_NIC_NIE_ZAZNACZYLES="Tu n'as rien marqué"
export TEXT_NIE_POBRALES_KLUCZY="Tu n'as pas téléchargé de la liste des clés"

#########################################################################################################################################################################
#tlumaczenia_config
export lang1="français!polski!english"
export TEXT_CONFIG1="La configurateur NeteXt73"
export TEXT_CONFIG2="La menu de configuration de NeteXt73"
export TEXT_CONFIG3="La couleur des inscriptions surligné"
export TEXT_CONFIG4="L'adresse des kernels payants:"
export TEXT_CONFIG5="L'adresse de version testing:"
export TEXT_CONFIG6="La langue du programme:"
export TEXT_CONFIG7="Supprime les fichiers de configuration:"
export TEXT_CONFIG8="Les fichiers de configuration du script NeteXt73 sont supprimés"
export TEXT_CONFIG9="Le profil APM:"
export TEXT_CONFIG10="Le profil de Kernel:"
export TEXT_CONFIG11="Utilise le profil sélectionné de kernel"
export TEXT_CONFIG12="Laisse la copie des fichiers *.deb dans /var/cache/apt/archives"

#########################################################################################################################################################################
#tlumaczenia_deinstalator
export TEXT_MENU_DEINSTALATOR1="Supprime kernel"		
export TEXT_MENU_DEINSTALATOR2="Supprime kernel - expert"	
export TEXT_MENU_DEINSTALATOR3="Désinstalle le broadcom"	
export TEXT_MENU_DEINSTALATOR4="Désinstalle l'APM"
export TEXT_MENU_DEINSTALATOR5="Désinstalle le microcode et le firmware"
export TEXT_MENU_DEINSTALATOR6="Supprime nettoyage cyclique de mémoire cache"
export TEXT_MENU_DEINSTALATOR7="Désinstalle NeteXt73"
export TEXT_DEINSTALATOR="Les désinstallateurs de système."
export TEXT_DEINSTALATOR1="Sélectionne l'option:"
export TEXT_DEINSTALATOR2="Est ce que tu es sûr que tu veux supprimer le package de pilotes de wifi broadcom?"
export TEXT_DEINSTALATOR3="La suppression du package fermé de pilotes broadcom a des conséquences pour l'ensemble du système, y compris les kernels restants installés sur ton système"
export TEXT_DEINSTALATOR4="Actuellement tu utilises:"
export TEXT_DEINSTALATOR5="pour ne pas les supprimer par hasard, ils ne vont pas être visible sur la liste suivante.\n\n Si la liste est vide, cela signifie que c'est ton seul kernel.\n\nSélectionne le kernel que tu souhaites supprimer:"
export TEXT_DEINSTALATOR6="la version de kernel"
export TEXT_DEINSTALATOR7="Tu as supprimé les kernels inutiles."
export TEXT_DEINSTALATOR8="Tu as arrêté le processus de supprimation des kernels inutils"
export TEXT_DEINSTALATOR10="Es-tu sûr que tu veux supprimer le script d'APM?"
export TEXT_DEINSTALATOR11="Es-tu sûr que tu veux supprimer le microcode et le firmware pour CPU et GPU?"
export TEXT_BRAK_KERNELI="Il n'y est rien kernels à supprimer."

#########################################################################################################################################################################
#tlumaczenia_gosc
export TEXT_GOSC1="Ajoute ou supprime le compte invité"
export TEXT_GOSC2="Ajoute le compte d'invité"
export TEXT_GOSC3="Supprime le compte d'invité"
export TEXT_GOSC4="Après avoir entré le mot de passe, la session de compte d'invité sera désactivé"
export TEXT_GOSC5="Après avoir entré le mot de passe, la session de compte d'invité sera activé"
export TEXT_INFO="\n\nPRÊT !!! - presse enter"

#########################################################################################################################################################################
#tlumaczenia_grub
export TEXT_SKRYPTEXT_10="Ta entrée actuelle dans le GRUB, c'est:"
export TEXT_SKRYPTEXT_11="Qu'est ce que tu veux faire?"
export TEXT_GRUB4A="Créer la sauvegarde du fichier de configuration du GRUB"
export TEXT_GRUB5A="Restaurer le fichier de configuration de GRUB"
export TEXT_GRUB6A="Injecter les entrées sélectionnées dans le GRUB en utilisant le créateur"
export TEXT_GRUB7A="Injecter manuellement les entrées dans le GRUB "
export TEXT_GRUB8="Faire la sauvegarde de fichier"
export TEXT_GRUB9="Tu as arrêté le processus de sauvegarde."
export TEXT_GRUB10="Restauration du fichier /etc/default/grub de sauvegarde."
export TEXT_GRUB11="Tu as arrêté le processus de restauration de sauvegarde."
export TEXT_GRUB12="Il n'y a pas de fichier de sauvegarde."
export TEXT_GRUB13="Il n'y a pas été de sauvegarde de fichier grub, le fichier grub.backup va être créé automatiquement dans le dossier"
export TEXT_GRUB14="Quel est ta plateforme?"
#export TEXT_GRUB15="Les paramètres optimals pour la plupart des ordinateurs"
#export TEXT_GRUB16="Sandy et ivy bridge /i3-i7/ avec une carte graphique intégrée Intel"
export TEXT_GRUB17="Les paramètres de rétro-éclairage de la matrice"
export TEXT_GRUB18="les paramètres qui sont utilisés en cas de problèmes avec les paramètres par défaut"
export TEXT_GRUB19="Corrigé"
export TEXT_GRUB_STD="Intel (Core 2 Duo minimum) ou AMD (minimum K8 Series)"
export TEXT_GRUB_INTEL="Intel i3-i5-i7 - Sandy/Ivy Bridge, Haswell avec une carte graphique intégrée Intel"
export TEXT_GRUB_RADEON="Radeon DPM - pilotes graphiques libres. Prévu uniquement pour la version du noyau v26.xx (basé sur 3.11)"
export TEXT_GRUB21="L'approbation finale des changements.\n"
export TEXT_GRUB21A="Introduit des changements en conformité avec les directives antérieures"
export TEXT_GRUB21B="Mode avancé"
export TEXT_GRUB21C="Permet l'édition de l'entrée"
export TEXT_GRUB22="Apporte des modifications ou accepte l'entrée sélectionnée:"
export TEXT_GRUB23="Pour les utilisateurs avancés seulement. Soyez prudent!\nApporte des modifications ou reviens au menu précédent"
export TEXT_NETBIT_MENU18="Réglez le temps au bout duquel menu GRUB disparaît:"
export TEXT_NETBIT_MENU19="Entre le mot de passe de compte root ou ferme cette fenêtre."

#########################################################################################################################################################################
#tlumaczenia_kernele
export TEXT_INSTLATOR1="<b>AVERTISSEMENT !!</b> - Installe le kerel de e X t 7 3, script d'APM, CPU, microcode et du microprogramme pour l'ordinateur de fonctionner correctement."
export TEXT_MENU_INSTALATOR3="Locals"
export TEXT_MENU_INSTALATOR4="Seuls entête"
export TEXT_MENU_INSTALATOR5="ppa mainline"
export TEXT_PPA_1="Sélectionne ta version du système, ce qui suggère:"
export TEXT_RODZAJ_SYSTEMU="Version du système"
export TEXT_LISTA_KERNELI="Liste des kernels pour Ubuntu"
export TEXT_ZAZNACZ_KERNEL="Sélectionne kernel que tu souhaite télécharger."
export TEXT_STEROWNIKI1="pas trouvé kernel pour la version de votre système"
export TEXT_INSTALOWAC="INSTALLER"
export TEXT_INSTALOWAC_KERNEL="a été téléchargé. \n\nSi tu souhaite installer automatiquement, clique:\n\nOUI\n"
export TEST_INSTALOWAC_KERNEL2="Le commande d'installation est enregistré dans le presse-papiers. Vous pouvez le coller dans le terminal à l'aide de raccourcis clavier:\n\nSHIFT+INSERT ou CTRL+SHIFT+V\n"
export TEST_INSTALOWAC_KERNEL3="Dans un moment l'installation du kernel va commencer"
export TEST_INSTALOWAC_KERNEL4="basé sur les fichiers téléchargés:"
export TEST_INSTALOWAC_KERNEL5="Le chemin d'accès de fichiers téléchargés est enregistré dans le presse-papiers. Vous pouvez le coller dans le terminal à l'aide de raccourcis clavier:\n\nSHIFT+INSERT ou CTRL+SHIFT+V\n"
export TEXT_INSTALOWAC_KERNEL6="Tu n'as pas reçu les fichiers d'installation, essaye de nouveau ."
export TEXT_INSTALOWAC_KERNEL7="Tu as déjà installé cette version du noyau.\nAvant de réinstaller tu as besoin de le supprimer."
export TEXT_STRONA1="Entrez le chemin d'amandes à payer. \nSi vous ne l'avez pas s'il vous plaît contacter: Tomasz e X t 7 3 Miś,mail:ext73@wp.pl"
export TEXT_K8="K8 - de Intel C2D, AMD K8"
export TEXT_DEBI1="Indique le fichier linux-headers ou linux-image, lequel tu veux installer:"

#########################################################################################################################################################################
#tlumaczenia_kontakt
export TEXT_KONTAKT_Z_AUTORAMI="Le contact avec les auteurs:"
export TEXT_NETBIT="NetBit73 - développement l'installateur graphique NeteXt73"
export TEXT_EXT="e X t 7 3 - préparation des kernels et du script d'APM"
export TEXT_FADEMIND="FadeMind - la traduction en anglais des textes et des bêta tests"
export TEXT_KAROLINA="Karolina Franieczek - la traduction allemande"
export TEXT_ENEDIL="enedil - la traduction française"
#
#########################################################################################################################################################################
#tlumaczenia_logi
export TEXT_LOGI0="La version actuelle du kernel:"
export TEXT_LOGI1="Les versions installées des kernels:"
export TEXT_LOGI2="Informations sur le matériel:"
export TEXT_LOGI6="Le statut des scripts d'optimisation:"
export TEXT_LOGI7="OUI, une mise à jour est disponible"
export TEXT_LOGI8="Propriétaire"
export TEXT_LOGI9="Entrée supplémentaire dans la section de GRUB:"
export TEXT_LOGI10="Les versions des fichiers:"
export TEXT_LOGI12="Les informations sur le système"
export TEXT_SKRYPT="Script"
export TEXT_WYGENERUJ="génére des journaux"

#########################################################################################################################################################################
#tlumaczenia_microcode
export TEXT_MICROCODE1="Tu as déjà installé le dernier firmware et le microcode pour CPU et GPU.\nAucune mise à jour disponible."
export TEXT_MICROCODE2="Tu n'as pas installé le dernier microcode.\nDans un moment l'installation va commencer."

#########################################################################################################################################################################
#tlumaczenia_monitor
export TEXT_MONITOR1="Sélectionne les programmes que tu souhaite exécuter:"

#########################################################################################################################################################################
#tlumaczenia_netext73
export TEXT_WERSJA="Tu peux mettre à jour le programme NeteXt'73 à la version"
export TEXT_LICENCJA="Licence"
export TEXT_BUG="Signale une erreur"
export TEXT_CHANGELOG="Liste des modifications"
export TEXT_PASSWD="Le mot de passe n'est pas correct. Arrêter le logiciel dans le mode root?"
export TEXT_PASSWD1="Entrer le mot de passe"

#########################################################################################################################################################################
#tlumaczenia_nvidia

#########################################################################################################################################################################
#tlumaczenia_radeon

#########################################################################################################################################################################
#tlumaczenia_ram
export TEXT_NETBIT_RAM1="Vide le cache immédiatement"
export TEXT_NETBIT_RAM2="La mémoire cache doit être vidé après avoir passé le pourcentage d'utilisation de la RAM "
export TEXT_RAM6="Dans un moment, sera exécuté vidér de mémoire utilisé. Si vous ne voulez pas faire cela, fermez cette fenêtre."
export TEXT_RAM7="Statut avant:"
export TEXT_RAM8="Statut après:"

#########################################################################################################################################################################
#tlumaczenia_tasksel
export TEXT_TASKSEL1="Dans un moment, seront installés les services de serveur. Si vous ne voulez pas faire cela, fermez cette fenêtre."

#########################################################################################################################################################################
#tlumaczenia_update
export TEXT_UPDATE1="Mets à jour"
export TEXT_UPDATE1a="Que veux-tu mettre à jour?"
export TEXT_UPDATE2="Mets à jour système"
export TEXT_UPDATE3="Mets à jour NeteXt'73"
export TEXT_UPDATE4="Aucune mise à jour disponible"
export TEXT_UPDATE5="Tu peux mettre à jour à la version"
export TEXT_UPDATE6="Veux-tu installer une mise à jour disponible pour NeteXt73 ?"
export TEXT_UPDATE7="Tnstaller tous"
export TEXT_UPDATE8="Installez les mises à jour disponibles"
export TEXT_INSTALACJA_NOWEJ="Installation d'une nouvelle version de NeteXt73"
export TEXT_STABLE="La dernière version stable du kernel"
export TEXT_MICROCODE1="Vous avez déjà installé le dernier firmware et le microcode pour CPU et GPU.\nAucune mise à jour disponible."
export TEXT_ZAINSTALOWANY="Le programme Netext73 a été installé.\nExécuter ce programme de: OUTILS/ACCESSOIRES."
export TEXT_BRAK_DANYCH="Serveurs pas disponibles. Vérifiez votre connexion Internet ou réessayez plus tard."

#########################################################################################################################################################################
#tlumaczenia_uslugi
export TEXT_MENU_USLUGI="Sélectionnez la section dans laquelle vous souhaitez apporter des modifications:"
export TEXT_MENU_USLUGI1="Gére les services SysV"
export TEXT_MENU_USLUGI1A="Gére les services Upstart"
export TEXT_MENU_USLUGI1B="Gére les services SysV - mode expert"
export TEXT_MENU_USLUGI1C="Gére les services Upstart - mode expert"
export TEXT_MENU_USLUGI1D="Afficher la liste des services avec leur statut"
export TEXT_MENU_USLUGI2="Sélectionnez les services à activer ou désactiver."
export TEXT_MENU_USLUGI3="Nom du service"
export TEXT_MENU_USLUGI4="Activé"
export TEXT_MENU_USLUGI5="Désactivé"
export TEXT_MENU_USLUGI6="Sélectionner des services de gestion."
export TEXT_MENU_USLUGI7="Démarration"
export TEXT_MENU_USLUGI8="Sélectionnez les services que vous souhaitez démarrer ou arrêter, supprimer ou ajouter à autostart."
export TEXT_MENU_USLUGI9="Service"
export TEXT_MENU_USLUGI10="Statut"
export TEXT_MENU_USLUGI11="Le numéro de processus"
export TEXT_MENU_USLUGI12="Tu gére le service:"
export TEXT_MENU_USLUGI22A="Démarre le service"
export TEXT_MENU_USLUGI22B="Arrête le service"
export TEXT_MENU_USLUGI22C="Met le service au démarrage automatique"
export TEXT_MENU_USLUGI22D="Désactiver le service de démarrage automatique"
export TEXT_MENU_USLUGI30="Le service sera activé"
export TEXT_MENU_USLUGI31="Entrez le mot de passe de compte root ou fermer cette fenêtre."
export TEXT_MENU_USLUGI32="Service \$a1 sera activé et ajouté à autostart."
export TEXT_MENU_USLUGI33="Le service sera désactivé."
export TEXT_MENU_USLUGI34="Le service est désactivé."
export TEXT_MENU_USLUGI35="Le service est déjà actif."
export TEXT_MENU_USLUGI36="Cela va désactiver le service \$a1 de démarrage automatique."
export TEXT_MENU_USLUGI37="Le service est déjà inactive."
export TEXT_MENU_USLUGI38="La liste des processus avec leurs statuts:"
export TEXT_MENU_USLUGI39="Nom"
export TEXT_BRAK="aucun"

#########################################################################################################################################################################
#tlumaczenia_procedury
export BRAKNETA="<span color=\"$kolor_textu\">Serveurs pas disponibles. Vérifiez votre connexion Internet ou réessayez plus tard.</span>"
export TEXT_PROCEDURA_4="Veux-tu installer linux-firmware-nonfree ?"
export TEXT_POBIERANIE="<span color=\"$kolor_textu\">L'information est téléchargé du serveur. Attende!</span>"
export TEXT_NETEXT2="optimiseur de système"
export TEXT_POB1="s/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Vitesse de téléchargement: \2\/s, \3/ restantes"
export TEXT_POB2="Je télécharge les fichiers:"
export TEXT_INFO1="<br>Les kernels et le script d'APM - e t X 7 3<br>Le script NeteXt'73 - NetBit73<br>Traduction anglaise: Thomas Przybył /FadeMind/<br>Traduction allemande: Karolina Franieczek"
export TEXT_PROCEDURA_1="Installation de kernel e X t 7 3"
export TEXT_PROCEDURA_2="Installation du microcode pour la plate-forme $komputerek"
export TEXT_PROCEDURA_3="Suppression du microcode pour la plate-forme $komputerek"
export TEXT_PROCEDURA_6="Installation des scripts d'APM"
export TEXT_PROCEDURA_8_1="Change APM du profil actuel au "
export TEXT_PROCEDURA_9="Suppression des scripts d'APM"
export TEXT_PROCEDURA_13="Enregistrement des modifications dans le fichier de configuration de GRUB"
export TEXT_PROCEDURA_14="Installation des pilotes pour cartes graphiques Radeon"
export TEXT_PROCEDURA_15="Installation des pilotes pour cartes graphiques Nvidia"
export TEXT_KERNEL1="Les versions du kernel suivants seront supprimés:"
export TEXT_KERNEL2="Le kernel a été installé.\n\nAprès avoir cliqué sur OK\n les fichiers téléchargés seront supprimés.\n\nLes modifications exigent le redémarrage du système.\n\nClique OK"
export TEXT_PLATFORMA1="Tu as sélectionné la plate-frome"
export TEXT_PLATFORMA2=".\nAVERTISSEMENT !!\nRéinstallation des kernels installés n'est pas recommandée."
export TEXT_ZAZNACZ="marque"
export TEXT_WYBIERZ_KERNEL="sélectionne la version du kernel à installer dans la liste ci-dessous:"
export TEXT_ZNITY1="installé?"
export TEXT_GRUB1="Suppression d'entrées non désirées dans le fichier"
export TEXT_GRUB2="Les changements dans le fichier sont effectuées"
export TEXT_GRUB3="L'installation a été annulée. Commençons par le début, parce que la poursuite peut causer des dommages au système! Recommencez faire des changements dans le GRUB."
export TEXT_WYMAGANY_RESTART="Redémarrage apporte des changements."
export TEXT_INFO2="L'installation a été annulée. Les fichiers téléchargés sont dans:"
export TEXT_ZAMKNIJ_PROGRAM="Téléchargement interrompu. L'application va fermer dans 25 secondes."
export TEXT_RESTART="Est-tu sûr que tu redémarre l'ordinateur?"
#często powtarzane
export TEXT_INFORMACJA="L'INFORMATION"
export TEXT_INSTALACJA1="Entre le mot de passe de compte root ou ferme cette fenêtre."
export TEXT_INSTALACJA2="\n\nPRÊT !!! - presse enter"
export TEXT_INST1="Installation des relations qui sont nécessaires au bon fonctionnement du programme."
export TEXT_MENU="menu"
export TEXT_NIE="Non"
export TEXT_OPIS="description"
export TEXT_POWROT="Arrête"
export TEXT_STEROWNIK="Sélectionne le pilot"
export TEXT_STEROWNIKI1="il n'y a pour ta version du système"
export TEXT_STEROWNIKI2="L'Installateur des pilotes pour les cartes graphiques:"
export TEXT_STEROWNIKI3="L'Installateur n'a pas trouvé de la carte graphique supporté."
export TEXT_SUMA_KONTROLNA="ATTENTION! Les checksums sont incorrectes. Télécharge à nouveau le fichier."
export TEXT_TAK="Oui"
export TEXT_UWAGA="ATTENTION"
export TEXT_ZAMKNIJ="Ferme"
export TEXT_ZAZNACZ="marque"

#########################################################################################################################################################################

#tlumaczenia_skrypty
export TEXT_SKRYPT1="L'ensemble des scripts"
export MENU3="Supprime tous les fichiers de configuration"
export MENU4="Tue les processus zombie"
export MENU5="Xterm"
export MENU6="Synchronise l'heure d'Internet."
export MENU7="Activer le protocole IPv6" 
export MENU8="Désactiver le protocole IPv6"
export MENU9="Backdoor SSHD test"
export TEXT_ZOMBIE1="La liste des processus zombie"
export TEXT_ZOMBIE2="Il n'y a pas de processus zombie."
export TEXT_CONFIG1="Il n'y a pas des fichiers de configuration á supprimer."
export TEXT_BACK_CRITIC="ATTENTION: On a trouvé des séries Fokirtor dans le processus SSHD:"
export TEXT_BACK_OK="OK: rien menace dans les processus SSHD."



#########################################################################################################################################################################






