#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#APM

cd /tmp/netext73
rm *.html -f
rm /tmp/netext73/*.txt -f; rm /tmp/netext73/*.sh -f
stan_apm=""
export wersja_apm=$(ls /opt/NeteXt73/APM/advanced_power_management_by_ext73_* | cut -d '_' -f 6 | tail -n 1 | sed 's/.tar.gz//')
#zapamiętanie configu jeżeli był niepełen config
if [ -e  ~/.netext73/apm_status ] && [ "$(cat ~/.netext73/apm_status | wc -l)" != "8" ]; then
    #sprawdzanie czy jest włączony jakiś APM
    if [ "$(ls /etc/pm/power.d/)" != "" ] && [ "$(ls /etc/pm/power.d/advanced_power_management_by_ext73* -Fl | grep '*' | cut -d '_' -f 7)" = "" ];then
      naglowek > instaluj.sh
      echo "sudo chmod a+x /etc/pm/power.d/advanced_power_management_by_ext73_conservative*" >> instaluj.sh
      instalacja
    fi
    #sprawdzenie stanu czeków
    stan_apm_config
fi
petla_duza="tak"
while [ $petla_duza = "tak" ]; do
	stan_apm #sprawdzenie stanu instalacji
	if [ "$stan_apm" = "-" ]; then
		#instalacja APM
		yad-netext --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="$TEXT_APM1"
		if [ $? = 0 ]; then
		      naglowek > instaluj.sh
		      apm_inst >> instaluj.sh
		      if [ -e ~/.netext73/apm_status ]; then
			  apm_zmiana_config >> instaluj.sh
		      fi
		      instalacja2
		      stan_apm  #sprawdzenie stanu instalacji
		fi
	fi
	
	#sprawdzenie stanu czeków
	stan_apm_config
	
	aktualny_apm=$(echo $stan_apm | awk '{print $1}')
	menu_apm=$(echo "!conservative-conservative!ondemand-ondemand!intel-performance!intel-powersave!performance-conservative!performance-ondemand" | sed  "s/$aktualny_apm//" | sed 's/!!/!/')
	menu=$(echo "$aktualny_apm$menu_apm" | sed 's/!!/!/')
	
	if [ "$stan_apm" != "-" ]; then
		aa=$(yad-netext --center --title="$nazwa_skryptu" --width=410 --window-icon="/opt/NeteXt73/ikony/apm.png"  --image="/opt/NeteXt73/ikony/apm.png" --form \
		--field="$TEXT_WERSJA_APM:RO" --field="$TEXT_AKTUALNY_PROFIL_APM:RO" --field="$TEXT_ZMIEN_PROFIL_APM:CB" \
		"$(ls /etc/pm/power.d/ | cut -d "_" -f 7 | head -n 1)" "$aktualny_apm" "$menu" \
		--field="$TEXT_FIX1:CHK" "$wififix" \
		--field="$TEXT_FIX2:CHK" "$wifionoff" \
		--field="$TEXT_FIX3:CHK" "$btfix" \
		--field="$TEXT_FIX4:CHK" "$rts5139fix" \
		--field="$TEXT_FIX5:CHK" "$wifin" \
		--field="$TEXT_FIX6:CHK" "$turbooff" \
		--field="$TEXT_PLANISTA:CB" "$bfqfix_menu" \
		--field="$(echo $TEXT_PLANISTA | sed 's/HDD/SSD\/FLASH/'):CB" "$ssdfix_menu" \
		--button="gtk-ok:0" --button="$TEXT_ZAMKNIJ:1" )
		
		klawisz=$?
		if [ $klawisz = 0 ]; then 
			a=$(echo $aa | cut -d "|" -f 3)
			export wififix=$(echo $aa | cut -d "|" -f 4)
			export wifionoff=$(echo $aa | cut -d "|" -f 5)
			export btfix=$(echo $aa | cut -d "|" -f 6)
			export rts5139fix=$(echo $aa | cut -d "|" -f 7)
			export wifin=$(echo $aa | cut -d "|" -f 8)
			export turbooff=$(echo $aa | cut -d "|" -f 9)
			export bfqfix=$(echo $aa | cut -d "|" -f 10)
			export ssdfix=$(echo $aa | cut -d "|" -f 11)
					
			#uruchomienie aktualizacji gdy zaszła jakś zmiana
			if [ "$a" = "$aktualny_apm" ] && [ "$wififix_przed" = "$wififix" ] && [ "$wifionoff_przed" = "$wifionoff" ] && [ "$btfix_przed" = "$btfix" ] && [ "$rts5139fix_przed" = "$rts5139fix" ] && [ "$wifin_przed" = "$wifin" ] && [ "$bfqfix_przed" = "$bfqfix" ] && [ "$ssdfix_przed" = "$ssdfix" ] && [ "$turbooff_przed" = "$turbooff" ]; then
			    petla_duza="nie"
			    rm *.txt -f *.sh
			else
				naglowek > instaluj.sh
				if [ "$a" != "-" ]; then
					apm_zmiana $a "advanced_power_management_by_ext73_$a*" >> instaluj.sh
				elif [ "$a" = "-" ]; then
					yad-netext --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEXT_APM2"
					naglowek > instaluj.sh
					apm_inst >> instaluj.sh
					if [ -e ~/.netext73/apm_status ]; then
					    apm_zmiana_config >> instaluj.sh
					fi
				fi
				instalacja2
				#zapisanie stanu apm po zmianie
				stan_apm_config czeki
			fi
		fi
	fi
	if [ -z "$aa" ]; then
	      petla_duza="nie"
	      rm *.txt -f *.sh
	fi
done

