#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#APM
	cd /tmp
	rm *.html -f
	rm /tmp/*.txt -f; rm /tmp/*.sh -f
	stan_apm=""
	wget $adres_skryptow/APM2/index.html -O apm.txt  2>&1 | pobieranie2 
	export wersja_apm=$(cat apm.txt | grep "href=.*advanced" | cut -d '"' -f 2 | cut -d '_' -f 6 | head -n 1 | sed 's/.tar.gz//')
petla_duza="tak"
while [ $petla_duza = "tak" ]; do
	stan_apm
	if [ "$stan_apm" = "-" ]; then
		#instalacja APM
		yad-netext --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="$TEXT_APM1"
		if [ $? = 0 ]; then
		      naglowek > instaluj.sh
		      apm_inst >> instaluj.sh
		      instalacja
		      stan_apm
		fi
	fi

	#sprawdzenie stanu APM wifi FIX
	if [ "$(grep 'echo auto > $ii' /etc/pm/power.d/advanced_power_management_by_ext73_*)" = "" ];then
	    wififix="FALSE"
	else
	    wififix="TRUE"
	fi
	#włączenie wyłączenie wifi
	if [ "$(grep 'echo 1 > $wifi' /etc/pm/power.d/advanced_power_management_by_ext73_*)" = "" ];then
	    wifionoff="FALSE"
	else
	    wifionoff="TRUE"
	fi

	#sprawdzenie stanu bt FIX
	if [ "$(grep 'echo 1 > $bt' /etc/pm/power.d/advanced_power_management_by_ext73_*)" = "" ];then
	    btfix="FALSE"
	else
	    btfix="TRUE"
	fi

	#sprawdzenie stanu APM rts5139 FIX
	if [ "$(grep 'sudo modprobe rts5139' /etc/pm/power.d/advanced_power_management_by_ext73_*)" = "" ];then
	    rts5139fix="FALSE"
	else
	    rts5139fix="TRUE"
	fi
	#sprawdzenie wifi N
	if [ -e /etc/modprobe.d/wifin.conf ] ;then
	    wifin="FALSE"
	else 
	    wifin="TRUE"
	fi
	
	wifin_przed=$wifin
	wififix_przed=$wififix
	wifionoff_przed=$wifionoff
	btfix_przed=$btfix
	rts5139fix_przed=$rts5139fix
	
	aktualny_apm=$(echo $stan_apm | awk '{print $1}')
	if [ "$aktualny_apm" = "conservative-conservative" ];then
	    menu="conservative-conservative!ondemand-ondemand!intel-performance!intel-powersave!performance-conservative!performance-ondemand"
	elif [ "$aktualny_apm" = "ondemand-ondemand" ];then
	    menu="ondemand-ondemand!conservative-conservative!intel-performance!intel-powersave!performance-conservative!performance-ondemand"
	elif [ "$aktualny_apm" = "intel-performance" ];then
	    menu="intel-performance!conservative-conservative!ondemand-ondemand!intel-powersave!performance-conservative!performance-ondemand"
	elif [ "$aktualny_apm" = "intel-powersave" ];then
	    menu="intel-powersave!intel-performance!conservative-conservative!ondemand-ondemand!performance-conservative!performance-ondemand"
	elif [ "$aktualny_apm" = "performance-conservative" ];then
	    menu="performance-conservative!intel-powersave!intel-performance!conservative-conservative!ondemand-ondemand!performance-ondemand"
	elif [ "$aktualny_apm" = "performance-ondemand" ];then
	    menu="performance-ondemand!intel-powersave!intel-performance!conservative-conservative!ondemand-ondemand!performance-conservative"
	else
	    menu="conservative-conservative!ondemand-ondemand!intel-performance!intel-powersave!performance-conservative!performance-ondemand"
	fi

	if [ "$stan_apm" != "-" ]; then
		aa=$(yad-netext --center --title="$nazwa_skryptu" --width=410 --window-icon="/opt/NeteXt73/ikony/apm.png" --form \
		--field="$TEXT_WERSJA_APM:RO" --field="$TEXT_AKTUALNY_PROFIL_APM:RO" --field="$TEXT_ZMIEN_PROFIL_APM:CB" \
		"$(ls /etc/pm/power.d/ | cut -d "_" -f 7 | head -n 1)" "$aktualny_apm" "$menu" \
		--field="$TEXT_FIX1:CHK" "$wififix" \
		--field="$TEXT_FIX2:CHK" "$wifionoff" \
		--field="$TEXT_FIX3:CHK" "$btfix" \
		--field="$TEXT_FIX4:CHK" "$rts5139fix" \
		--field="$TEXT_FIX5:CHK" "$wifin" \
		--button="gtk-ok:0" --button="$TEXT_POWROT:1" )
		 
		klawisz=$?; a=$(echo $aa | cut -d "|" -f 3); export wififix=$(echo $aa | cut -d "|" -f 4);export wifionoff=$(echo $aa | cut -d "|" -f 5); export btfix=$(echo $aa | cut -d "|" -f 6); export rts5139fix=$(echo $aa | cut -d "|" -f 7); export wifin=$(echo $aa | cut -d "|" -f 8)
		#uruchomienie aktualizacji gdy zaszła jakś zmiana
		if [ "$a" = "$aktualny_apm" ] && [ "$wififix_przed" = "$wififix" ] && [ "$wifionoff_przed" = "$wifionoff" ] && [ "$btfix_przed" = "$btfix" ] && [ "$rts5139fix_przed" = "$rts5139fix" ] && [ "$wifin_przed" = "$wifin" ]; then
		    petla_duza="nie"
		    rm *.txt -f *.sh
		else
			if [ "$a" = "conservative-conservative" ]; then
				naglowek > instaluj.sh
				apm_zmiana $a "$wersja_apm1*$wersja_apm" >> instaluj.sh
				instalacja2
			elif [ "$a" = "ondemand-ondemand" ]; then
				naglowek > instaluj.sh
				apm_zmiana $a "$wersja_apm2*$wersja_apm" >> instaluj.sh
				instalacja2
			elif [ "$a" = "intel-performance" ]; then
				naglowek > instaluj.sh
				apm_zmiana $a "$wersja_apm3*$wersja_apm" >> instaluj.sh
				instalacja2
			elif [ "$a" = "intel-powersave" ]; then
				naglowek > instaluj.sh
				apm_zmiana $a "$wersja_apm4*$wersja_apm" >> instaluj.sh
				instalacja2
			elif [ "$a" = "performance-conservative" ]; then
				naglowek > instaluj.sh
				apm_zmiana $a "$wersja_apm5*$wersja_apm" >> instaluj.sh
				instalacja2
			elif [ "$a" = "performance-ondemand" ]; then
				naglowek > instaluj.sh
				apm_zmiana $a "$wersja_apm6*$wersja_apm" >> instaluj.sh
				instalacja2
			elif [ "$a" = "-" ]; then
				yad-netext --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEXT_APM2"
				naglowek > instaluj.sh
				apm_inst >> instaluj.sh
				instalacja2
			fi
		fi
	fi
	if [ -z "$aa" ]; then
	      petla_duza="nie"
	      rm *.txt -f *.sh
	fi
done
#1 conservative-conservative
#2 ondemand-ondemand
#3 intel-performance
#4 intel-powersave
#5 performance-conservative
#6 performance-ondemand
