#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil) - enedil@outlook.com
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#config

adres_kerneli_premium
if [ -e ~/.netext73/apm_status ]; then
    apm_stat=$(cat ~/.netext73/apm_status | sed 's/.* //')
else
    apm_stat=""
fi
if [ -e ~/.netext73/instalator_kerneli ]; then
    ik=$(cat ~/.netext73/instalator_kerneli)
else
    ik=""
fi
if [ -e ~/.netext73/instalator_kerneli ]; then
    ik=$(cat ~/.netext73/instalator_kerneli)
else
    ik="i7 - Intel Sandy Bridge, Ivy Bridge, Haswell"
fi

if [ -e ~/.netext73/kernel_automat ]; then
    if [ "$(cat ~/.netext73/kernel_automat)" = "TRUE" ]; then
	automatyczna_instalacja="TRUE"
    else  
	automatyczna_instalacja="FALSE"
    fi
else
    automatyczna_instalacja="FALSE"
fi


if [ -e ~/.netext73/archiwum_deb ]; then
    if [ "$(cat ~/.netext73/archiwum_deb)" = "TRUE" ]; then
	archiwum_deb="TRUE"
    else  
	archiwum_deb="FALSE"
    fi
else
    archiwum_deb="FALSE"
fi

if [ "$(cat /opt/NeteXt73/procedury | grep https.*dl)" != "" ]; then
    https_link="TRUE"
else
    https_link="FALSE"
fi
konfiguracja=$(yad --title="$TEXT_CONFIG1" --width="155" --height="320" --window-icon="/opt/NeteXt73/ikony/config.png" --text="<span color=\"$kolor_textu\">$TEXT_CONFIG2</span>" --form \
--field="$TEXT_CONFIG7:CB" --field="$TEXT_CONFIG4" --field="$TEXT_CONFIG5" --field="$TEXT_CONFIG6:CB" --field="$TEXT_CONFIG9:RO" --field="$TEXT_CONFIG10:RO" --field="$TEXT_CONFIG11:CHK" --field="$TEXT_CONFIG12:CHK" --field="HTTPS On/Off:CHK" "$TEXT_NIE!$TEXT_TAK" "$adres_premium" "$adres_testing" "$lang1" "$apm_stat" "$ik" "$automatyczna_instalacja" "$archiwum_deb" "$https_link" \
--button="$TEXT_CONFIG3:2" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
klawisz=$?
if [ $klawisz = 2 ]; then
	kolor=$(yad --color --window-icon="/opt/NeteXt73/ikony/config.png" --text="$TEXT_CONFIG2")
	klawisz=$?
	if [ "$klawisz" = "0" ];then
	      echo $kolor > ~/.netext73/kolor_textu
	      killall -9 yad && cd /opt/NeteXt73 && ./NeteXt73
	fi
fi

if [ $klawisz = 0 ]; then 
	if [ "$(echo "$konfiguracja" | grep "$TEXT_TAK")" != "" ]; then
		rm ~/.netext73/* -f
		yad --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEXT_CONFIG8" --timeout=5
	else
		echo $konfiguracja | grep 'http' | cut -d "|" -f 2 > ~/.netext73/kernel_premium
		echo $konfiguracja | grep 'http' | cut -d "|" -f 3 > ~/.netext73/netext_testing
		echo $konfiguracja | cut -d "|" -f 4 > ~/.netext73/jezyk
		echo $konfiguracja | cut -d "|" -f 7 > ~/.netext73/kernel_automat
		echo $konfiguracja | cut -d "|" -f 8 > ~/.netext73/archiwum_deb
		echo $konfiguracja | cut -d "|" -f 9 > ~/.netext73/https_link
		if [ "$https_link" = "TRUE" ] && [ "$(cat ~/.netext73/https_link)" = "FALSE" ]; then
		    xterm -T instalator -e bash -c "sudo sed -i 's/https:/http:/g' /opt/NeteXt73/procedury"
		elif [ "$https_link" = "FALSE" ] && [ "$(cat ~/.netext73/https_link)" = "TRUE" ]; then
		    xterm -T instalator -e bash -c "sudo sed -i 's/http:/https:/g' /opt/NeteXt73/procedury"
		fi
		killall -9 yad && cd /opt/NeteXt73 && ./NeteXt73	      
	fi
fi