#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#config

#kasowanie starych configów
rm ~/.netext73/https_link -f
rm ~/.netext73/server_no -f

if [ -e ~/.netext73/apm_status ]; then
	apm_stat=$(cat ~/.netext73/apm_status | sed 's/.* //' | head -n 1)
else
	apm_stat=""
fi
if [ -e ~/.netext73/instalator_kerneli ]; then
	ik=$(cat ~/.netext73/instalator_kerneli)
else
	ik=""
fi
if [ -e ~/.netext73/instalator_kerneli ]; then
	ik=$(cat ~/.netext73/instalator_kerneli)
else
	ik="i7 - Intel Sandy Bridge, Ivy Bridge, Haswell"
fi

if [ -e ~/.netext73/kernel_automat ]; then
	if [ "$(cat ~/.netext73/kernel_automat)" = "TRUE" ]; then
	      automatyczna_instalacja="TRUE"
	else  
	      automatyczna_instalacja="FALSE"
	fi
else
	automatyczna_instalacja="FALSE"
fi


if [ -e ~/.netext73/archiwum_deb ]; then
	if [ "$(cat ~/.netext73/archiwum_deb)" = "TRUE" ]; then
	      archiwum_deb="TRUE"
	else  
	      archiwum_deb="FALSE"
	fi
else
	archiwum_deb="FALSE"
fi

if [ -e ~/.netext73/root_mode ] && [ "$(cat ~/.netext73/root_mode)" = "TRUE" ]; then
	root_mode="TRUE"
else
	root_mode="FALSE"
fi

KEY="$(echo $RANDOM)"
#zmienne losowe
res1=$(mktemp --tmpdir=/tmp/netext73 netext73_1.XXXXXXXX)
res2=$(mktemp --tmpdir=/tmp/netext73 netext73_2.XXXXXXXX)

yad-netext --plug=$KEY --tabnum=1 --form \
--field="$TEXT_CONFIG7:CB" --field="$TEXT_CONFIG4" --field="$TEXT_CONFIG6:CB" --field="$TEXT_CONFIG9:RO" --field="$TEXT_CONFIG10:RO" --field="$TEXT_CONFIG11:CHK" --field="$TEXT_CONFIG12:CHK" --field="NeteXt'73 -root mode:CHK" "$TEXT_NIE!$TEXT_TAK" "" "$lang1" "$apm_stat" "$ik" "$automatyczna_instalacja" "$archiwum_deb" "$root_mode" --button="$TEXT_CONFIG3:2" &> $res1 &
yad-netext --plug=$KEY --tabnum=2 --color --init-color=$kolor_textu &> $res2 &
yad-netext --notebook --key=$KEY --center --title="$nazwa_skryptu1 " --tab="$TEXT_CONFIG2" --tab="$TEXT_CONFIG3" --window-icon="/opt/NeteXt73/ikony/config.png" --on-top --width=540 --height=400 --button="gtk-ok:0" --button="$TEXT_POWROT:1"
klawisz=$?
if [ "$klawisz" = 0 ]; then 
	if [ "$(grep "$TEXT_TAK" $res1)" != "" ]; then
		#rm ~/.netext73/* -f
		yad-netext --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --text="$TEXT_CONFIG8" --timeout=5
	else
		if [ "$(cat $res1 | grep '@' | cut -d "|" -f 2)" != "" ];then
		      cat $res1 | grep '@' | cut -d "|" -f 2 > ~/.netext73/kernel_premium
		fi
		cat $res1 | cut -d "|" -f 3 > ~/.netext73/jezyk
		cat $res1 | cut -d "|" -f 6 > ~/.netext73/kernel_automat
		cat $res1 | cut -d "|" -f 7 > ~/.netext73/archiwum_deb
		cat $res1 | cut -d "|" -f 8 > ~/.netext73/root_mode
		cat $res2 > ~/.netext73/kolor_textu
		#kasowanie śmieci w configach
		for i in $(echo jezyk kernel_automat archiwum_deb root_mode kernel_premium kolor_textu); do
			sed -i '/.*yad-netext.*/ d' ~/.netext73/$i
			sed -i '/^[ \t]*$/ d' ~/.netext73/$i
		done

		if [ "$root_mode" != "$(cat ~/.netext73/root_mode)" ]; then
			rm -fr /tmp/netext73
			killall yad-netext
			dymek -i $ikona_info1 "$TEXT_INFORMACJA" "$TEXT_CONFIG13"
		fi    
	fi
fi
rm -f $res1 $res2
