#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#usuwanie zbędnych kerneli

cd /tmp
rm /tmp/*.txt -f; rm /tmp/*.sh -f
usun=$(yad-netext --center --title="$nazwa_skryptu" --width=420 --window-icon="/opt/NeteXt73/ikony/delete.png" --text="<span color=\"$kolor_textu\">$TEXT_DEINSTALATOR</span>" --form --field="$TEXT_DEINSTALATOR1:CB"  "$TEXT_MENU_DEINSTALATOR1!$TEXT_MENU_DEINSTALATOR2!$TEXT_MENU_DEINSTALATOR4!$TEXT_MENU_DEINSTALATOR5!$TEXT_MENU_DEINSTALATOR6!$TEXT_MENU_DEINSTALATOR7" --button="gtk-ok:0" --button="$TEXT_POWROT:1"  )
klawisz=$?; usun=$(echo $usun | cut -d "|" -f 1)
#Usuń broadcom
#if [ "$usun" = "$TEXT_MENU_DEINSTALATOR3" ] ; then
#	yad-netext --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --text="$TEXT_DEINSTALATOR2"
#	if [ $? = 0 ]; then
#		dymek  -i $warning1 "$TEXT_UWAGA" "$TEXT_DEINSTALATOR3"
#		naglowek > instaluj.sh
#		broadcom_usun >> instaluj.sh
#		instalacja
#	fi
	
if [ "$usun" = "$TEXT_MENU_DEINSTALATOR4" ]; then
	naglowek > instaluj.sh
	yad-netext --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --text="$TEXT_DEINSTALATOR10"
	if [ $? = 0 ]; then
	      apm_usun >> instaluj.sh
	      instalacja
	fi

elif [ "$usun" = "$TEXT_MENU_DEINSTALATOR5" ]; then
	naglowek > instaluj.sh
	yad-netext --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --text="$TEXT_DEINSTALATOR11"
	if [ $? = 0 ]; then
	      microcode_usun >> instaluj.sh
	      instalacja
	fi

elif [ "$usun" = "$TEXT_MENU_DEINSTALATOR1" ]; then
	#generowanie listy na podstawie plików linux-image
	dpkg -l | grep 'linux-image*'  | grep -v -E "linux-image-extra*|linux-image-generic|linux-image-$(uname -r)" | awk '{print $2}' > /tmp/lista_kerneli.txt
elif [  "$usun" = "$TEXT_MENU_DEINSTALATOR2" ]; then
	#generowanie listy na podstawie plików linux-image oraz linux-headers
	dpkg -l | grep 'linux-image'   | grep -v -E "linux-image-$(uname -r)"   | awk '{print $2}' > /tmp/lista_kerneli.txt
	dpkg -l | grep 'linux-headers' | grep -v -E "linux-headers-$(uname -r)" | awk '{print $2}'>> /tmp/lista_kerneli.txt
elif [  "$usun" = "$TEXT_MENU_DEINSTALATOR6" ]; then
	naglowek > instaluj.sh
	RAMIK_USUN >> instaluj.sh
	instalacja
elif [  "$usun" = "$TEXT_MENU_DEINSTALATOR7" ]; then
	xterm -T instalator -e bash -c "echo \"$TEXT_INSTALACJA1\"; sudo rm -rf /opt/NeteXt73 /usr/share/applications/NeteXt73.desktop /usr/share/pixmaps/NeteXt73.png /usr/local/bin/install_netext; echo -e \"$TEXT_INSTALACJA2\";killall -9 yad-netext"
fi
if [ "$usun" =  "$TEXT_MENU_DEINSTALATOR1" ] || [ "$usun" =  "$TEXT_MENU_DEINSTALATOR2" ]; then
  if [ "$(cat lista_kerneli.txt)" != "" ]; then
  a=$(yad-netext --center --height=440 --width=560 --window-icon="/opt/NeteXt73/ikony/delete.png" --text="$TEXT_DEINSTALATOR4  <span color=\"$kolor_textu\"><b> linux-image-$(uname -r) </b></span>,\n$TEXT_DEINSTALATOR5\n" --title="Kernel wywalator" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --checklist --list  --column="$TEXT_ZAZNACZ" --column="$TEXT_DEINSTALATOR6"  $(sed -e '/^[^#]/s:^:FALSE :' /tmp/lista_kerneli.txt ))
	if [ $? = 0 ]; then
		if [ "$a" != "" ]; then
			if [ "$usun" = "$TEXT_MENU_DEINSTALATOR1" ]; then

				#spradzanie czy są pliki linux-headers na podstawie linux-images
				echo $a > /tmp/lista_kerneli.txt; cat /tmp/lista_kerneli.txt | sed -e "s/-generic//g" -e "s/linux-image/linux-headers/g"  >> /tmp/lista_kerneli.txt
				cat /tmp/lista_kerneli.txt | sed 's/TRUE//g' | tr '|' '\n' > /tmp/lista.txt
				for SOFT in $(cat /tmp/lista.txt)
				do
					  if [ "$(dpkg -l $SOFT | grep 'ii' | awk '{print $1}'| head -n1)" = "ii" ]; then
					      echo $SOFT >> /tmp/kasuj.txt
					  fi
				done
			else
				echo $a > /tmp/lista_kerneli.txt; cat /tmp/lista_kerneli.txt| tr '|' '\n' > kasuj.txt
			fi
			#proces kasowania kerneli
			naglowek > instaluj.sh
			usun_kernel >> instaluj.sh
			echo "nie" > /tmp/ok.txt
			instalacja
			if [ "$(cat /tmp/ok.txt)" = "tak" ]; then
				dymek -i $ikona_info1 "$TEXT_INFORMACJA" "$TEXT_DEINSTALATOR7"
			else
				dymek -i $warning1 "$TEXT_UWAGA" "$TEXT_DEINSTALATOR8"
			fi
		fi
	else
		rm /tmp/*.txt -f; rm /tmp/*.sh -f
	fi
  else
	dymek -i $warning1 "$TEXT_UWAGA" "$TEXT_BRAK_KERNELI"
  fi
fi
