#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#usuwanie zbędnych kerneli

cd /tmp/netext73
rm /tmp/netext73/*.txt -f; rm /tmp/netext73/*.sh -f
usun=$(yad-netext --center --title="$nazwa_skryptu" --width=420 --window-icon="/opt/NeteXt73/ikony/delete.png" --image="/opt/NeteXt73/ikony/delete.png" --text="<span color=\"$kolor_textu\">$TEXT_DEINSTALATOR</span>" --form --field="$TEXT_DEINSTALATOR1:CB"  "$TEXT_MENU_DEINSTALATOR1!$TEXT_MENU_DEINSTALATOR2!$TEXT_MENU_DEINSTALATOR4!$TEXT_MENU_DEINSTALATOR5!$TEXT_MENU_DEINSTALATOR7" --button="gtk-ok:0" --button="$TEXT_POWROT:1"  )
klawisz=$?; usun=$(echo $usun | cut -d "|" -f 1)

#usuwanie apm
if [ "$usun" = "$TEXT_MENU_DEINSTALATOR4" ]; then
	naglowek > instaluj.sh
	yad-netext --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="$TEXT_DEINSTALATOR10"
	if [ $? = 0 ]; then
		apm_usun >> instaluj.sh
		instalacja
	fi
#usuwanie microcode 
elif [ "$usun" = "$TEXT_MENU_DEINSTALATOR5" ]; then
	naglowek > instaluj.sh
	yad-netext --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="$TEXT_DEINSTALATOR11"
	if [ $? = 0 ]; then
		microcode_usun >> instaluj.sh
		instalacja
	fi
#usuwanie netexta
elif [  "$usun" = "$TEXT_MENU_DEINSTALATOR7" ]; then
	x-terminal-emulator -e bash -c "echo \"$TEXT_INSTALACJA1\";sudo apt-get purge netext73; sudo rm -rf /opt/NeteXt73 /usr/share/applications/NeteXt73.desktop /usr/share/pixmaps/NeteXt73.png /usr/local/bin/install_netext; echo -e \"$TEXT_INSTALACJA2\";killall -9 yad-netext"
#usuwanie kerneli
elif [ "$usun" =  "$TEXT_MENU_DEINSTALATOR1" ] || [ "$usun" =  "$TEXT_MENU_DEINSTALATOR2" ]; then
	petla="tak"
	while [ $petla = "tak" ]; do
		#usuwanie kerneli
		if [ "$usun" = "$TEXT_MENU_DEINSTALATOR1" ]; then
			#generowanie listy na podstawie plików linux-image
			dpkg -l | grep 'linux-image*'  | grep -v -E "linux-image-extra*|linux-image-generic" | awk '{print $2}'| grep -x -v "linux-image-$(uname -r)" > /tmp/netext73/lista_kerneli.txt
		#usuwanie kerneli expert
		elif [  "$usun" = "$TEXT_MENU_DEINSTALATOR2" ]; then
			#generowanie listy na podstawie plików linux-image oraz linux-headers
			dpkg -l | grep 'linux-image'   | awk '{print $2}' | grep -x -v "linux-image-$(uname -r)" > /tmp/netext73/lista_kerneli.txt
			dpkg -l | grep 'linux-headers'  | awk '{print $2}' | grep -x -v "linux-headers-$(uname -r)" >> /tmp/netext73/lista_kerneli.txt
		fi
		if [ "$(cat lista_kerneli.txt)" != "" ]; then
		a=$(yad-netext --center --height=440 --width=560 --window-icon="/opt/NeteXt73/ikony/delete.png" --text="$TEXT_DEINSTALATOR4  <span color=\"$kolor_textu\"><b> linux-image-$(uname -r) </b></span>,\n$TEXT_DEINSTALATOR5\n" --title="$TEXT_MENU_DEINSTALATOR1" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --checklist --list  --column="$TEXT_ZAZNACZ" --column="$TEXT_DEINSTALATOR6"  $(sed -e '/^[^#]/s:^:FALSE :' /tmp/netext73/lista_kerneli.txt ))
			if [ $? = 0 ]; then
				if [ "$a" != "" ]; then
					if [ "$usun" = "$TEXT_MENU_DEINSTALATOR1" ]; then

						#spradzanie czy są pliki linux-headers na podstawie linux-images
						echo $a > /tmp/netext73/lista_kerneli.txt; cat /tmp/netext73/lista_kerneli.txt | sed -e "s/-generic//g" -e "s/linux-image/linux-headers/g"  >> /tmp/netext73/lista_kerneli.txt
						cat /tmp/netext73/lista_kerneli.txt | sed 's/TRUE//g' | tr '|' '\n' > /tmp/netext73/lista.txt
						for SOFT in $(cat /tmp/netext73/lista.txt)
						do
							if [ "$(dpkg -l $SOFT | grep 'ii' | awk '{print $1}'| head -n1)" = "ii" ]; then
								echo $SOFT >> /tmp/netext73/kasuj.txt
							fi
						done
					else
						echo $a > /tmp/netext73/lista_kerneli.txt; cat /tmp/netext73/lista_kerneli.txt | tr '|' '\n' > kasuj.txt
					fi
					#proces kasowania kerneli
					naglowek > instaluj.sh
					usun_kernel >> instaluj.sh
					instalacja2
				else
					petla="nie"
				fi
			else
				rm /tmp/netext73/*.txt -f; rm /tmp/netext73/*.sh -f
				petla="nie"
			fi
		      
		else
		      dymek -i $warning1 "$TEXT_UWAGA" "$TEXT_BRAK_KERNELI"
		      petla="nie"
		fi
	done
fi
