#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#instalator sterowników do grafik Nvidia
cd /tmp

usun(){
rm *.txt* -f; rm *.sh -f; rm *.html* -f
rm *.deb -f
rm nvidia-settings -f
}

usun
if  [ "$bit2" = "i386" ]; then
	dymek -i $warning1 "$TEXT_UWAGA" "$TEXT_STEROWNIKI1"
else
	if [ "$1" = "nvidia" ]; then
	    wget $adres_sterownikow/index.html  2>&1 | pobieranie 
	    if [ -e index.html ]; then
		cat index.html | grep "href=" ./index.html   | cut -d '"' -f 2 | grep 'nvidia-' | grep $bit2 | sed 's/.deb//' | grep -v -E "nvidia-settings.*"> 1a.txt
		cat 1a.txt | sort -r > 2a.txt
		lista=$(cat 2a.txt | tr '\n' '!' | sed -e '$s/!$//g' )
		ster=$(yad-netext --center --title="$nazwa_skryptu" --width=410 --window-icon="/opt/NeteXt73/ikony/nvidia.png" --text="$TEXT_STEROWNIKI2 <span color=\"$kolor_textu\"><b>Nvidia</b></span>" --form --field="$TEXT_STEROWNIK:CB" "$lista" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
		klawisz=$?; ster=$(echo $ster | cut -d "|" -f 1)
		echo $ster
		if [ "$ster" != "" ] && [ "$klawisz" = "0" ]; then
				  if [ "$(echo $ster | cut -d '_' -f 2 | cut -d "." -f1 )" -gt "331" ];then
					  nv_set="nvidia-settings_331.20-0ubuntu8_amd64.deb"
					  yad_wget $adres_sterownikow/1.txt $adres_sterownikow/$nv_set $adres_sterownikow/$ster.deb
				  elif  [ "$(echo $ster | cut -d '_' -f 2 | cut -d "." -f1 )" -ge "337" ]; then
					  nv_set="nvidia-settings"
					  yad_wget $adres_sterownikow/1.txt $adres_sterownikow/$nv_set $adres_sterownikow/$ster.deb
				  else
					  yad_wget $adres_sterownikow/1.txt $adres_sterownikow/$ster.deb
				  fi  
				  if [ -e $ster.deb ] && [ -e $nv_set ] && [ "$(grep $(md5sum $ster.deb) 1.txt)" != "" ] && [ "$(grep $(md5sum $nv_set) 1.txt)" != "" ]; then
					  echo "nie" > /tmp/ok.txt
					  naglowek > instaluj.sh
					  nvidia >> instaluj.sh
					  instalacja
				  elif [ -e $ster.deb ] && [ "$(grep $(md5sum $ster.deb) 1.txt)" != "" ]; then
					  echo "nie" > /tmp/ok.txt
					  naglowek > instaluj.sh
					  nvidia >> instaluj.sh
					  instalacja 
				  else
					  yad-netext --center --error --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_SUMA_KONTROLNA"
				  fi
		fi
	    fi
	elif [ "$1" = "radeon" ]; then
		if [ "$(lspci | grep VGA | awk '{print tolower($0)}' | grep radeon)" = "" ] || [ "$(glxinfo | grep 'AMD Radeon HD' | sed 's/.*HD //g' | sed 's/ .*//g')" -le 5000 ]; then
		  dymek -i $warning1 "$TEXT_UWAGA" "$TEXT_STEROWNIKI3"
		else
		    wget $adres_sterownikow/index.html  2>&1 | pobieranie 
		    if [ -e index.html ]; then
			cat index.html | grep "href=" ./index.html   | cut -d '"' -f 2 | grep 'fglrx_' | grep $bit2 | sed 's/.deb//' >> 1a.txt
			cat 1a.txt | sort -r > 2a.txt
			lista=$(cat 2a.txt | tr '\n' '!' | sed -e '$s/!$//g' )
			ster=$(yad-netext --center --title="$nazwa_skryptu" --width=410 --window-icon="/opt/NeteXt73/ikony/radeon.png" --text="$TEXT_STEROWNIKI2 <span color=\"$kolor_textu\"><b>Radeon</b></span>" --form --field="$TEXT_STEROWNIK:CB" "$lista" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
				klawisz=$?; ster=$(echo $ster | cut -d "|" -f 1)
				if [ "$ster" != "" ] && [ "$klawisz" = "0" ]; then
				  	  yad_wget $adres_sterownikow/1.txt $adres_sterownikow/$ster.deb $adres_sterownikow/$(echo $ster.deb | sed "s/fglrx/fglrx-amdcccle/")
					  if [ -e $ster.deb ] && [ -e $ster.deb ] && [ "$(grep $(md5sum $ster.deb) 1.txt)" != "" ] && [ "$(grep $(md5sum $ster.deb) 1.txt)" != "" ]; then
						  echo "nie" > /tmp/ok.txt
						  naglowek > instaluj.sh
						  radeon >> instaluj.sh
						  instalacja
					  else
						  yad-netext --center --error --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_SUMA_KONTROLNA"
					  fi
				fi
		    fi
		fi
	fi
fi
usun
