#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#Grub edytor

cd /tmp
rm *.html -f
petla_duza="tak"
while [ $petla_duza = "tak" ]; do
rm /tmp/*.txt -f; rm /tmp/*.sh -f

if [ "$(grep "GRUB_CMDLINE_LINUX=" /etc/default/grub)" != "GRUB_CMDLINE_LINUX=\"\"" ];  then
      g1="$TEXT_TAK : $(grep GRUB_CMDLINE_LINUX=\" /etc/default/grub | sed "s/GRUB_CMDLINE_LINUX=//")"
else
      g1="-"
fi
#sprawdzenie czasu timeout
if [ "$(grep 'GRUB_TIMEOUT' /etc/default/grub | sed 's/.*=//g')" != "" ]; then
    czas=$(grep 'GRUB_TIMEOUT' /etc/default/grub | sed 's/.*=//g')
else
    czas="3"
fi

#GRUB
sciezka="/etc/default"
echo "nie" > /tmp/ok.txt

grub=$(yad-netext --center --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/grub.png" --form --field="$TEXT_SKRYPTEXT_10" --field="$TEXT_SKRYPTEXT_11:CB" "$(grep GRUB_CMDLINE_LINUX=\" /etc/default/grub | sed 's/GRUB_CMDLINE_LINUX=//' | cut -d '"' -f 2)" "$TEXT_GRUB6A!$TEXT_GRUB4A!$TEXT_GRUB5A!$TEXT_GRUB7A" --button="gtk-ok:0" --button="$TEXT_POWROT:1"  )
klawisz=$?; grub=$(echo $grub | cut -d "|" -f 2)
	if [ $klawisz = 0 ]; then 
	#backup pliku grub
	if [ "$grub" = "$TEXT_GRUB4A" ]; then
	      echo "nie" > /tmp/ok.txt
	      xterm -T Grub -e bash -c "echo \"$TEXT_GRUB8 /etc/default/grub\";sudo cp $sciezka/grub $sciezka/grub.backup -f; echo -e \"$TEXT_INSTALACJA2\"; read ent; echo 'tak' > /tmp/ok.txt"
	      if [ "$(cat /tmp/ok.txt)" = "nie" ]; then
		      dymek  -i $warning1 "$TEXT_UWAGA" "$TEXT_GRUB9"
	      fi
	#przywrócenie pliku grub z backupu
	elif [ "$grub" = "$TEXT_GRUB5A" ]; then
	      if [ -e $sciezka/grub.backup ]; then
		    echo "nie" > /tmp/ok.txt
		    xterm -T Grub -e bash -c "echo \"$TEXT_GRUB10\"; sudo cp $sciezka/grub.backup $sciezka/grub -f; sudo update-grub; echo -e \"$TEXT_INSTALACJA2\"; read ent; echo 'tak' > /tmp/ok.txt"
		    if [ "$(cat /tmp/ok.txt)" = "nie" ]; then
			  dymek  -i $warning1 "$TEXT_UWAGA" "$TEXT_GRUB11"
		    fi
	      else
		    dymek  -i $warning1 "$TEXT_UWAGA" "$TEXT_GRUB12"
	      fi
	#dokonaie zmian we wpisach w pliku grub
	elif [ "$grub" = "$TEXT_GRUB6A" ]; then
	      if [ -e $sciezka/grub.backup ]; then
		    echo 'tak' > /tmp/ok.txt
	      else
		    dymek -i $warning1 "$TEXT_UWAGA" "$TEXT_GRUB13 $sciezka"
		    #kasowanie starych wpisów w grub
		    xterm -e bash -c "sudo cp $sciezka/grub $sciezka/grub.backup -f; echo -e \"$TEXT_INSTALACJA2\"; read ent;  echo 'tak' > /tmp/ok.txt"
	      fi
	      if [ "$(cat /tmp/ok.txt)" = "tak" ]; then
		    wpis_grub=$(grep GRUB_CMDLINE_LINUX=\" /etc/default/grub | sed 's/GRUB_CMDLINE_LINUX=//' | cut -d '"' -f 2)
		    if [ "$(echo $wpis_grub | grep 'Windows')" != "" ] ; then
			menu1="acpi_osi='!Windows 2012' acpi_osi=Linux@acpi_osi=Linux"
		    else
			menu1="acpi_osi=Linux@acpi_osi='!Windows 2012' acpi_osi=Linux"
		    fi
		    if [ "$(echo $wpis_grub | grep '915')" != "" ] ; then
			menu2="$TEXT_GRUB_INTEL@$TEXT_GRUB_STD@$TEXT_GRUB_RADEON"
		    elif [ "$(echo $wpis_grub | grep 'radeon')" != "" ] ; then
			menu2="$TEXT_GRUB_RADEON@$TEXT_GRUB_INTEL@$TEXT_GRUB_STD"
		    else
			menu2="$TEXT_GRUB_STD@$TEXT_GRUB_INTEL@$TEXT_GRUB_RADEON"
		    fi
		    if [ "$(echo $wpis_grub | grep 'vendor')" != "" ] ; then
			menu3="$TEXT_GRUB19@standard"
		    else
			menu3="standard@$TEXT_GRUB19"
		    fi
		    acpi_wpis=$( yad-netext --center --height=240 --width=610 --button="gtk-ok:0" --button="$TEXT_POWROT:1" --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --form  --item-separator="@"\
		    --field="$TEXT_SKRYPTEXT_10" \
		    --field="ACPI:CB" --field="$TEXT_GRUB14:CB" --field="$TEXT_GRUB17:CB" \
		    --field="$TEXT_NETBIT_MENU18:NUM" \
		    "$wpis_grub" \
		    "$menu1" \
		    "$menu2" \
		    "$menu3" \
		    "$czas[@-1..10[@1]]" )
		    if [ $? = 0 ]; then
			  w0=$(echo $acpi_wpis  | cut -d "|" -f 2)				#acpi Linux/Windows pcie_aspm=force
			  w1=$(echo $acpi_wpis  | cut -d "|" -f 3)				#
			  w2=$(echo $acpi_wpis  | cut -d "|" -f 4)				#podświetlenie
			  export w3=$(echo $acpi_wpis  | cut -d "|" -f 5 | sed 's/,.*//g' ) 	#grub timeout
			  if [ "$w0" = "acpi_osi='!Windows 2012' acpi_osi=Linux" ]; then w0="acpi_osi='!Windows 2012' acpi_osi=Linux pcie_aspm=force"
			  else 
			      w0="acpi_osi=Linux pcie_aspm=force"
			  fi    
			  if [ "$w1" = "$TEXT_GRUB_STD" ]; then		w1=" acpi_enforce_resources=lax"
			  elif [ "$w1" = "$TEXT_GRUB_INTEL" ]; then 	w1=" acpi_enforce_resources=lax i915.i915_enable_rc6=1 i915.i915_enable_fbc=1 i915.lvds_downclock=1 i915.semaphores=1"
			  elif [ "$w1" = "$TEXT_GRUB_RADEON" ]; then	w1=" acpi_enforce_resources=lax radeon.dpm=1"
			  fi
			  if [ "$w2" = "standard" ]; then      		w2=""
			  elif [ "$w2" = "$TEXT_GRUB19" ]; then  	w2=" acpi_backlight=vendor"
			  fi
			  wpis_grub=$(yad-netext --center --height=240 --width=600 --button="gtk-ok:0" --button="$TEXT_POWROT:1" --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --entry --text="$TEXT_GRUB22" --entry-text="$w0$w1$w2")
				    wpis_grub=$(echo $wpis_grub | cut -d "|" -f 2)
				    if [ "$wpis_grub" != "" ];then
					instaluj_grub
				    fi
		    fi
		fi
	#ręczna edycja wpisów w pliku grub
	elif [ "$grub" = "$TEXT_GRUB7A" ]; then
	    echo "nie" > /tmp/ok.txt
	    wpis_grub=$(yad-netext --center --height=240 --width=600 --button="gtk-ok:0" --button="$TEXT_POWROT:1" --title="$nazwa_skryptu" --entry --text="$TEXT_GRUB23" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --entry-text="$(grep GRUB_CMDLINE_LINUX=\" /etc/default/grub | cut -d "\"" -f 2)")
	    if [ $? = 0 ]; then
		    wpis_grub=$(echo $wpis_grub | cut -d "|" -f 2)
		    instaluj_grub
	    fi
	fi
	fi
if [ -z "$a" ]; then
	      petla_duza="nie"
	      rm *.txt -f
fi
done
