#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################

cd /tmp/netext73

if [ "$1" = "paypal" ]; then
	if [ "$USER" = "root" ]; then
		sudo -u $userek bash << EOF
		xdg-open 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=J6MV2T7WKPEAY'
EOF

	else
		xdg-open "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=J6MV2T7WKPEAY"
	fi

elif [ "$1" = "kontakty" ]; then
	if [ "$USER" = "root" ]; then
		sudo -u $userek bash << EOF
		KEY="$(echo $RANDOM)"
		#zmienne losowe
		res1=$(mktemp --tmpdir=/tmp/netext73 netext73_1.XXXXXXXX)
		res2=$(mktemp --tmpdir=/tmp/netext73 netext73_2.XXXXXXXX)
		res3=$(mktemp --tmpdir=/tmp/netext73 netext73_3.XXXXXXXX)

		yad-netext --plug=$KEY --tabnum=1 --icons --image-on-top --single-click --item-width="150" --read-dir="/opt/NeteXt73/kontakty" > $res1 &
		yad-netext --plug=$KEY --tabnum=2 --text-info --filename=/opt/NeteXt73/changelog > $res2 &
		yad-netext --plug=$KEY --tabnum=3 --text-info --filename=/opt/NeteXt73/LICENSE > $res3 &
		yad-netext --notebook --key=$KEY --center --title="$nazwa_skryptu1 " --tab="$TEXT_KONTAKT_Z_AUTORAMI" --tab="$TEXT_CHANGELOG" --tab="$TEXT_LICENCJA" --window-icon="/opt/NeteXt73/ikony/mail.png" --on-top --width=840 --height=400 --button="gtk-ok:1"
		klawisz=$?
		if [ "$klawisz" = "2" ]; then
			xdg-open "http://www.netext73.pl/2014/02/netext73-zgaszanie-bedow.html"
		fi
EOF
	else
		KEY="$(echo $RANDOM)"
		#zmienne losowe
		res1=$(mktemp --tmpdir=/tmp/netext73 netext73_1.XXXXXXXX)
		res2=$(mktemp --tmpdir=/tmp/netext73 netext73_2.XXXXXXXX)
		res3=$(mktemp --tmpdir=/tmp/netext73 netext73_3.XXXXXXXX)

		yad-netext --plug=$KEY --tabnum=1 --icons --image-on-top --single-click --item-width="150" --read-dir="/opt/NeteXt73/kontakty" > $res1 &
		yad-netext --plug=$KEY --tabnum=2 --text-info --filename=/opt/NeteXt73/changelog > $res2 &
		yad-netext --plug=$KEY --tabnum=3 --text-info --filename=/opt/NeteXt73/LICENSE > $res3 &
		yad-netext --notebook --key=$KEY --center --title="$nazwa_skryptu1 " --tab="$TEXT_KONTAKT_Z_AUTORAMI" --tab="$TEXT_CHANGELOG" --tab="$TEXT_LICENCJA" --window-icon="/opt/NeteXt73/ikony/mail.png" --on-top --width=840 --height=400 --button="gtk-ok:1" --button="$TEXT_BUG:2"
		klawisz=$?

		if [ "$klawisz" = "2" ]; then
			      xdg-open "http://www.netext73.pl/2014/02/netext73-zgaszanie-bedow.html"
		fi
	  
	fi
	rm -f $res1 $res2 $res3
else
	if [ "$USER" = "root" ]; then
		if [ -e ~/.netext73/jezyk ]; then
			if [ "$(cat ~/.netext73/jezyk)" = "polski" ];then
				sudo -u $userek bash << EOF
				xdg-open $adres_opisu
EOF
			else
				sudo -u $userek bash << EOF
				xdg-open $adres_opisu
EOF
			fi
		else
			sudo -u $userek bash << EOF
			xdg-open $adres_opisu
EOF
		fi
	else
		if [ -e ~/.netext73/jezyk ]; then
			if [ "$(cat ~/.netext73/jezyk)" = "polski" ];then
				xdg-open $adres_opisu
			else
				xdg-open $adres_opisu
			fi
		else
			xdg-open $adres_opisu
		fi
	fi


fi