#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################

cd /tmp/netext73

if [ "$1" = "paypal" ]; then
	
	if [ "$USER" = "root" ]; then
	      userek=$(cat /tmp/netext73/userek)
	      su $userek -c "xdg-open \"https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=J6MV2T7WKPEAY\""
	else
	      xdg-open "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=J6MV2T7WKPEAY"
	fi

elif [ "$1" = "kontakty" ]; then

	if [ "$USER" = "root" ]; then
		userek=$(cat /tmp/netext73/userek)
		su $userek -c "yad-netext --center --icons --title=\"$nazwa_skryptu\" --window-icon=\"/opt/NeteXt73/ikony/mail.png\" --image-on-top --item-width=\"150\" --read-dir=\"/opt/NeteXt73/kontakty\" \
		--button=\"gtk-ok:0\" --width=820 --height=260"
	else
		yad-netext --center --icons --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/mail.png" --image-on-top --item-width="150" --read-dir="/opt/NeteXt73/kontakty" \
		--button="gtk-ok:0" --width=820 --height=260 --single-click
	fi
	
else
	if [ "$USER" = "root" ]; then
		if [ -e ~/.netext73/jezyk ]; then
			userek=$(cat /tmp/netext73/userek)
			if [ "$(cat ~/.netext73/jezyk)" = "polski" ];then
				su $userek -c "xdg-open $adres_opisu"
			else
				su $userek -c "xdg-open $adres_opisu"
			fi
		else
			su $userek -c "xdg-open $adres_opisu"
		fi
	else
		if [ -e ~/.netext73/jezyk ]; then
			if [ "$(cat ~/.netext73/jezyk)" = "polski" ];then
				xdg-open $adres_opisu
			else
				xdg-open $adres_opisu
			fi
		else
			xdg-open $adres_opisu
		fi
	fi


fi