#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#instalator płatnych wersji

cd /tmp

menu1="i7 - Intel Sandy Bridge, Ivy Bridge"
menu1a="i7-PRO Haswell"
menu2="Brazos - AMD Athlon II, Phenom II, Brazos, Bulldozer"
menu2a="Brazos-PRO Piledriver, Steamroller"
menu3=$TEXT_K8
menu4="Atom - Intel Atom 64bit"


if [ "$(cat ~/.netext73/kernel_automat)" = "TRUE" ]; then
      kern="$(cat ~/.netext73/instalator_kerneli)"
else
    if [ "$1" = "K8" ]; then
	    kern="K8 - od Intel C2D, AMD K8"
    elif [ "$1" = "amd" ]; then
	    kern="Brazos - AMD Athlon II, Phenom II, Brazos, Bulldozer"
    elif [ "$1" = "amd_pro" ]; then
	    kern="Brazos-PRO Piledriver, Steamroller"
    elif [ "$1" = "i7" ]; then
	    kern="i7 - Intel Sandy Bridge, Ivy Bridge"
    elif [ "$1" = "i7_pro" ]; then
	    kern="i7-PRO Haswell"
    elif [ "$1" = "atom" ]; then
	    kern="Atom - Intel Atom 64bit"
    elif [ "$1" = "naglowki" ]; then
	    kern="$TEXT_MENU_INSTALATOR4"
    elif [ "$1" = "lokalne" ]; then
	    kern="$TEXT_MENU_INSTALATOR3"
    fi
    if [ "$1" = "premium" ]; then
	pliki="/opt/NeteXt73/kernel-premium"
	ikona="linux-premium.png"
    else
	pliki="/opt/NeteXt73/kernel"
	ikona="linux.png"
    fi
    if [ "$kern" = "" ]; then
	    yad-netext --center --icons --class="NeteXt'73" --name="NeteXt'73" --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/$ikona" \
	    --image="/opt/NeteXt73/ikony/netext73.png" --image-on-top --item-width="260" --read-dir="$pliki" --width="560" --height="330" \
	    --title="$nazwa_skryptu " --button="$TEXT_MENU_INSTALATOR5:4"  --button="$TEXT_POWROT:1" --single-click
	    klawisz=$?   
    fi
fi
#--button="$TEXT_MENU_INSTALATOR4:3" --button="$TEXT_MENU_INSTALATOR3:2" [ "$klawisz" = "2" ]; then kern="$TEXT_MENU_INSTALATOR3" elif [ "$klawisz" = "3" ]; then       kern="$TEXT_MENU_INSTALATOR4"
if [ "$klawisz" = "4" ]; then
      kern="$TEXT_MENU_INSTALATOR5"
fi

rodzaj=$(echo $kern | cut -d " " -f 1)

if [ "$kern" = "$menu1" ] || [ "$kern" = "$menu1a" ] || [ "$kern" = "$menu2" ] || [ "$kern" = "$menu2a" ] || [ "$kern" = "$menu3" ] || [ "$kern" = "$menu4" ] || [ "$(echo $kern | grep 'Intel C2D, AMD K8')" != "" ]; then
      echo $kern > ~/.netext73/instalator_kerneli
fi

rodzaj=$(echo $rodzaj | awk '{print tolower($0)}')

	if [ "$(echo $kern | grep i7)" != "" ] || [ "$(echo $kern | grep Brazos)" != "" ]; then
		if [ -e ~/.netext73/kernel_premium ] && [ "$(cat  ~/.netext73/kernel_premium)" != "" ]; then
		    str="$(cat ~/.netext73/kernel_premium)"
		    zrodlo=$(echo $str | sed -e "s/index.html//g")
		    strona="$zrodlo$rodzaj/"
		else
		    str=""
		    ##
		    strona=$(yad-netext --center --entry --width=610 --window-icon="/opt/NeteXt73/ikony/linux.png" --title="$nazwa_skryptu" --text="$TEXT_STRONA1" --entry-text="$str" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
		    klawisz=$?
		    if [ "$klawisz" = "1" ]; then
			    blad=1
		    else
			    if [ "$strona" != "" ]; then
				    if [ $? = 0 ]; then
					    echo $strona > ~/.netext73/kernel_premium
					    if [ "$strona" != "" ]; then
						    zrodlo=$(echo $strona | sed -e "s/index.html//g")
						    strona="$zrodlo$rodzaj/"
					    fi
				    fi
			    fi
		    fi
		fi
	elif [ "$(echo $kern | grep K8)" != "" ] || [ "$(echo $kern | grep Atom)" != "" ]; then
		strona="$adres_glowny/kernele/"
	#lokalne
	elif [ "$kern" = "$TEXT_MENU_INSTALATOR3" ]; then
		a=$(yad-netext --center --file-selection --filename="$download/" --title="$(echo $TEXT_DEB1 | sed 's/headers/headers ext73 /' | sed 's/image/image ext73 /')" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --width=650 --height=450 --button="gtk-ok:0" --button="$TEXT_POWROT:1")
		if [ $? = 0 ]; then
			if [ "$(echo $a | grep 'linux-image' | grep 'ext' | grep '.deb')" != "" ]; then
				cd $(echo $a | sed -e 's/linux.*//g');     b=$(echo $a | sed -e 's/linux-image/linux-headers/g')
				export sprawdzamy="tak"
			elif [ "$(echo $a | grep 'linux-headers' | grep 'ext' | grep '.deb')" != "" ]; then
				cd $(echo $a | sed -e 's/linux.*//g');     b=$(echo $a | sed -e 's/linux-headers/linux-image/g')
				export sprawdzamy="tak"
			else
				yad-netext --center --error --title="$nazwa_skryptu" --text="$(echo $TEXT_DEB1 | sed 's/:/!/' | sed 's/headers/headers ext73 /' | sed 's/image/image ext73 /')" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0"  --timeout=15 
				export sprawdzamy="nie"
			fi
			if [ "$sprawdzamy" = "tak" ]; then
				rm /tmp/kernel -fr; 	mkdir /tmp/kernel
				cd /tmp/kernel; 	cp $a $b /tmp/kernel/
				naglowek > instaluj.sh
				naglowek2 >> instaluj.sh
				instalacja
				cd /tmp; rm -rf kernel
				restart
			fi
		fi
	#tylko nagłówki
	elif [ "$kern" = "$TEXT_MENU_INSTALATOR4" ]; then
		a=$(yad-netext --center --file-selection --filename="$download/" --title="$(echo $TEXT_DEB1 | sed 's/lub linux-image//' | sed 's/headers/headers ext73/')" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --width=650 --height=450 --button="gtk-ok:0" --button="$TEXT_POWROT:1")
		if [ $? = 0 ]; then
		if [ "$(echo $a | grep 'linux-image' | grep 'ext' | grep '.deb')" != "" ]; then
			cd $(echo $a | sed -e 's/linux.*//g');	b=$(echo $a | sed -e 's/linux-image/linux-headers/g')
			rm /tmp/kernel -fr; 	mkdir /tmp/kernel
			cd /tmp/kernel;    		cp $b /tmp/kernel/
			xterm -T instalator -e bash -c "/usr/bin/yes | sudo dpkg -i linux-headers*"
		        restart
		elif [ "$(echo $a | grep 'linux-headers' | grep 'ext' | grep '.deb')" != "" ]; then
			cd $(echo $a | sed -e 's/linux.*//g')
			rm /tmp/kernel -fr; 	mkdir /tmp/kernel
			cd /tmp/kernel;		cp $a /tmp/kernel/
			xterm -T instalator -e bash -c "/usr/bin/yes | sudo dpkg -i linux-headers*"
			restart
		else
			yad-netext --center --error --title="$nazwa_skryptu"  --text="$(echo $TEXT_DEB1 | sed 's/:/!/' | sed 's/lub linux-image//' | sed 's/headers/headers ext73 /')" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0"  --timeout=15
		fi
		fi
	    
	elif [ "$kern" = "$TEXT_MENU_INSTALATOR5" ]; then
		cd /tmp; rm *.html -f
		strona="http://kernel.ubuntu.com/~kernel-ppa/mainline/"
		WERSJA_DISTRO=$(yad-netext --center --title="$nazwa_skryptu" --width=420 --window-icon="/opt/NeteXt73/ikony/linux.png" --text="$TEXT_PPA_1 <span color=\"$kolor_textu\">$(lsb_release -cs)</span>" --form --field="$TEXT_RODZAJ_SYSTEMU:CB"  "utopic!trusty!saucy!raring!quantal!precise" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
		klawisz=$?; export WERSJA_DISTRO=$(echo $WERSJA_DISTRO | cut -d "|" -f 1)
		if [ "$klawisz" = 0 ];then
			wget $strona  2>&1 | pobieranie 
			a=$(yad-netext --center --height=630 --width=410 --button="gtk-ok:0" --button="$TEXT_POWROT:1" --window-icon="/opt/NeteXt73/ikony/linux.png" --list $(grep 'href=' ./index.html | cut -d '"' -f 8 | grep $WERSJA_DISTRO | sed -e "s/-$WERSJA_DISTRO//g"   | sed -e 's/v//g' | sed 's/\(.*\)./\1/' | sort -r  | awk 'ORS=NR%3?"\t\t\t":"\n"') --column="" --text="$TEXT_LISTA_KERNELI <b><span color=\"$kolor_textu\">$WERSJA_DISTRO</span></b> \n\n$TEXT_ZAZNACZ_KERNEL" --title="Kernel instalator")
			klawisz=$?
			if [ "$klawisz" = 0 ] && [ "$a" != "" ];then
				a="v"$(echo $a | cut -d '|' -f 1)"-"$WERSJA_DISTRO
				rm index.html -f; rm $PWD/v$a-$WERSJA_DISTRO -rf
				mkdir $a; cd $a
				pobieranie_kerneli
				find $PWD -type f | grep -v -E "*.deb" | xargs rm -f
				if yad-netext --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="Kernel $a $TEXT_INSTALOWAC_KERNEL"; then
					echo $PWD > /tmp/katalog.txt
					xterm -T instalator -e bash -c "cd $(cat /tmp/katalog.txt) && /usr/bin/yes | sudo dpkg -i *.deb && rm katalog.txt -f"
					restart
				else
					echo -n "cd "$PWD" && /usr/bin/yes | sudo dpkg -i *.deb" | xclip -selection clipboard
					yad-netext --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEST_INSTALOWAC_KERNEL2"
					if [ "$?" = "1" ]; then
					      exit 1
					fi
				fi
			fi
		fi
	fi
  
	if [ "$kern" = "$menu1" ] || [ "$kern" = "$menu1a" ] || [ "$kern" = "$menu2" ] || [ "$kern" = "$menu2a" ] || [ "$kern" = "$menu3" ] || [ "$kern" = "$menu4" ] || [ "$(echo $kern | grep 'Intel C2D, AMD K8')" != "" ] && [ "$blad" != "1" ]; then
		if [ "$rodzaj" != "" ]; then
		if  [ "$bit2" = "i386" ]; then
			yad-netext --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_STEROWNIKI1"
		else
			rm index.html -f; wget $strona/index.html 2>&1 | pobieranie 
			lista_kerneli
			if [ "$klawisz" = "0" ] && [ "$blad" != "1" ] ; then
				export sprawdzamy="nie"
				dpkg -l |grep linux-image | awk '{print $2}' | grep $rodzaj | sed 's/linux-image-//g' | sed "s/-$rodzaj-ags-cfs//g" > 1.txt
				for kernel in $(cat 1.txt); do
					if [ "$(echo $a | grep $(echo $kernel))" != "" ]; then
					      export sprawdzamy="tak"
					fi
				done
				if [ "$sprawdzamy" = "nie" ]; then
					rm ./index.html -f; rm $a -rf
					mkdir $a; cd $a
					#wywołanie funkcji pobierania odpowiednich wersji kerneli
					pobieranie_kerneli
					if [ "$(grep $(md5sum linux-image*) 1.txt)" != "" ] && [ "$(grep $(md5sum linux-headers*) 1.txt)" != "" ]; then
						export sprawdzamy="nie"
						if [ -e linux-headers* ] && [ -e linux-image* ]; then
							if yad-netext --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --height=280 --width=590 --text="$TEST_INSTALOWAC_KERNEL3 $rodzaj $TEST_INSTALOWAC_KERNEL4\n\n$(ls *.deb)\n\n$TEXT_INSTALOWAC ?\n\n" ; then
								naglowek > instaluj.sh
								naglowek2 >> instaluj.sh
								instalacja
								#wywalenie plików po instalacji
								wywal_pobrane_pliki_kernela
								restart
							else
								echo -n "cd $PWD" | xclip -selection clipboard
								yad-netext --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEST_INSTALOWAC_KERNEL5"
							fi
						else
							dymek  -i $warning1 "$TEXT_UWAGA" "$TEXT_INSTALOWAC_KERNEL6"
						fi
					else
						yad-netext --center --error --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_SUMA_KONTROLNA"
					fi
				elif [ "$sprawdzamy" = "tak" ]; then
				      yad-netext --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_INSTALOWAC_KERNEL7"
				fi
			fi
		fi
		fi
	fi
