#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#instalator płatnych wersji

cd /tmp/netext73

#menu1="i7 - Intel Sandy Bridge, Ivy Bridge"
#menu1a="i7-PRO Haswell"
#menu2="Brazos - AMD Athlon II, Phenom II, Brazos, Bulldozer"
#menu2a="Brazos-PRO Piledriver, Steamroller"
#menu3=$TEXT_K8
#menu4="Atom - Intel Atom 64bit"
#menu5="Sandy Bridge"
#menu6="Ivy Bridge"
#menu7="Haswell"
#menu8="Broadwell"
#menu9="Brazos"
#menu10="Bulldozer"
#menu11="Piledriver"

if [ -e ~/.netext73/kernel_automat ] && [ -e ~/.netext73/instalator_kerneli ] && [ "$(cat ~/.netext73/kernel_automat)" = "TRUE" ]; then
	kern="$(cat ~/.netext73/instalator_kerneli)"
else
	if [ "$1" = "K8" ]; then
		kern="K8 - od Intel C2D, AMD K8"
	elif [ "$1" = "atom" ]; then
		kern="Atom - Intel Atom 64bit"
	elif [ "$1" = "sandy" ]; then
		kern="Sandy Bridge"
	elif [ "$1" = "ivy" ]; then
		kern="Ivy Bridge"
	elif [ "$1" = "haswell" ]; then
		kern="Haswell"
		export katalog2="2"
	elif [ "$1" = "broadwell" ]; then
		kern="Broadwell"
	elif [ "$1" = "brazos" ]; then
		kern="Brazos"
	elif [ "$1" = "bulldozer" ]; then
		kern="Bulldozer"
	elif [ "$1" = "piledriver" ]; then
		kern="Piledriver"
	elif [ "$1" = "amd" ]; then
		kern="Brazos - AMD Athlon II, Phenom II, Brazos, Bulldozer"
	elif [ "$1" = "amd_pro" ]; then
		kern="Brazos-PRO Piledriver, Steamroller"
	elif [ "$1" = "i7" ]; then
		kern="i7 - Intel Sandy Bridge, Ivy Bridge"
	elif [ "$1" = "i7_pro" ]; then
		kern="i7-PRO Haswell"
	elif [ "$1" = "naglowki" ]; then
		kern="$TEXT_MENU_INSTALATOR4"
	elif [ "$1" = "lokalne" ]; then
		kern="$TEXT_MENU_INSTALATOR3"
	fi
	if [ "$1" = "premium" ]; then
		pliki="/opt/NeteXt73/kernel-premium"
		ikona="linux-premium.png"
		export katalog2="2"
	elif [ "$1" = "old" ]; then
		pliki="/opt/NeteXt73/kernel-premium_old"
		ikona="linux-premium.png"
	else
		pliki="/opt/NeteXt73/kernel"
		ikona="linux.png"
		export katalog2=""
	fi
	if [ "$kern" = "" ]; then
		yad --center --icons --class="NeteXt'73" --name="NeteXt'73" --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/$ikona" \
		--image="/opt/NeteXt73/ikony/netext73.png" --image-on-top --item-width="$((200*$skala))" --read-dir="$pliki" --width="$((860*$skala))" --height="$((340*$skala))" \
		--title="$nazwa_skryptu " --button="$TEXT_MENU_INSTALATOR5:4"  --button="$TEXT_ZAMKNIJ:1" --single-click
		klawisz=$?   
	fi
fi

if [ "$klawisz" = "4" ]; then
	kern="$TEXT_MENU_INSTALATOR5"
fi

rodzaj=$(echo $kern | cut -d " " -f 1 | awk '{print tolower($0)}')

	#lokalne
	if [ "$kern" = "$TEXT_MENU_INSTALATOR3" ]; then
		a=$(yad --center --file-selection --filename="$download/" --title="$(echo $TEXT_DEB1 | sed 's/headers/headers ext73 /' | sed 's/image/image ext73 /')" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --width=$((650*$skala)) --height=$((450*$skala)) --button="gtk-ok:0" --button="$TEXT_POWROT:1")
		if [ $? = 0 ]; then
			if [ "$(echo $a | grep 'linux-image' | grep 'ext' | grep '.deb')" != "" ]; then
				cd $(echo $a | sed -e 's/linux.*//g');     b=$(echo $a | sed -e 's/linux-image/linux-headers/g')
				echo "tak" > /tmp/netext73/ok.txt
			elif [ "$(echo $a | grep 'linux-headers' | grep 'ext' | grep '.deb')" != "" ]; then
				cd $(echo $a | sed -e 's/linux.*//g');     b=$(echo $a | sed -e 's/linux-headers/linux-image/g')
				echo "tak" > /tmp/netext73/ok.txt
			else
				yad --center --error --title="$nazwa_skryptu" --text="$(echo $TEXT_DEB1 | sed 's/:/!/' | sed 's/headers/headers ext73 /' | sed 's/image/image ext73 /')" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0"  --timeout=15 
				echo "nie" > /tmp/netext73/ok.txt
			fi
			if [ "$(cat /tmp/netext73/ok.txt)" = "tak" ]; then
				rm /tmp/netext73/kernel -fr; 	mkdir /tmp/netext73/kernel
				cd /tmp/netext73/kernel; 	cp $a $b /tmp/netext73/kernel/
				naglowek > instaluj.sh
				sprawdz_gcc >> instaluj.sh
				instaluj_kernel >> instaluj.sh
				usun_lpt >> instaluj.sh
				instalacja2
				cd /tmp/netext73; rm -rf kernel
				restart
			fi
		fi
	#tylko nagłówki
	elif [ "$kern" = "$TEXT_MENU_INSTALATOR4" ]; then
		a=$(yad --center --file-selection --filename="$download/" --title="$(echo $TEXT_DEB1 | sed 's/lub linux-image//' | sed 's/headers/headers ext73/')" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --width=$((650*$skala)) --height=$((450*$skala)) --button="gtk-ok:0" --button="$TEXT_POWROT:1")
		if [ $? = 0 ]; then
		if [ "$(echo $a | grep 'linux-image' | grep 'ext' | grep '.deb')" != "" ]; then
			cd $(echo $a | sed -e 's/linux.*//g');	b=$(echo $a | sed -e 's/linux-image/linux-headers/g')
			rm /tmp/netext73/kernel -fr; 	mkdir /tmp/netext73/kernel
			cd /tmp/netext73/kernel;    	cp $b /tmp/netext73/kernel/
			xterm -T instalator -e bash -c "/usr/bin/yes | sudo dpkg -i linux-headers*"
		        restart
		elif [ "$(echo $a | grep 'linux-headers' | grep 'ext' | grep '.deb')" != "" ]; then
			cd $(echo $a | sed -e 's/linux.*//g')
			rm /tmp/netext73/kernel -fr; 	mkdir /tmp/netext73/kernel
			cd /tmp/netext73/kernel;		cp $a /tmp/netext73/kernel/
			xterm -T instalator -e bash -c "/usr/bin/yes | sudo dpkg -i linux-headers*"
			restart
		else
			yad --center --error --title="$nazwa_skryptu"  --text="$(echo $TEXT_DEB1 | sed -e 's/:/!/' -e 's/lub linux-image//' -e 's/headers/headers ext73 /')" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0"  --timeout=15
		fi
		fi
	#kernele PPA
	elif [ "$kern" = "$TEXT_MENU_INSTALATOR5" ]; then
		cd /tmp/netext73; rm *.html -f
		strona="http://kernel.ubuntu.com/~kernel-ppa/mainline/"
		WERSJA_DISTRO=$(yad --center --title="$nazwa_skryptu" --width=$((420*$skala)) --window-icon="/opt/NeteXt73/ikony/linux.png" --text="$TEXT_PPA_1 <span color=\"$kolor_textu\">$(lsb_release -cs)</span>" --form --field="$TEXT_RODZAJ_SYSTEMU:CB"  "$wersje_ubu" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
		klawisz=$?; export WERSJA_DISTRO=$(echo $WERSJA_DISTRO | cut -d "|" -f 1)
		if [ "$klawisz" = 0 ];then
			wget $strona  2>&1 | pobieranie 
			a=$(yad --center --height=$((630*$skala)) --width=$((410*$skala)) --button="gtk-ok:0" --button="$TEXT_POWROT:1" --window-icon="/opt/NeteXt73/ikony/linux.png" --list $(grep 'href=' ./index.html | cut -d '"' -f 8 | grep $WERSJA_DISTRO | sed -e "s/-$WERSJA_DISTRO//g" -e 's/v//g' -e 's/\(.*\)./\1/' | grep -v -E "3.8.13.28" | sort -r  | awk 'ORS=NR%3?"\t\t\t":"\n"') --column="" --text="$TEXT_LISTA_KERNELI <b><span color=\"$kolor_textu\">$WERSJA_DISTRO</span></b> \n\n$TEXT_ZAZNACZ_KERNEL" --title="Kernel instalator")
			klawisz=$?
			if [ "$klawisz" = 0 ] && [ "$a" != "" ];then
				a="v"$(echo $a | cut -d '|' -f 1)"-"$WERSJA_DISTRO
				rm index.html -f; rm $PWD/v$a-$WERSJA_DISTRO -rf
				mkdir $a; cd $a
				pobieranie_kerneli
				find $PWD -type f | grep -v -E "*.deb" | xargs rm -f
				if yad --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="Kernel $a $TEXT_INSTALOWAC_KERNEL"; then
					echo $PWD > /tmp/netext73/katalog.txt
					xterm -T instalator -e bash -c "cd $(cat /tmp/netext73/katalog.txt) && /usr/bin/yes | sudo dpkg -i *.deb && rm katalog.txt -f"
					restart
				else
					echo -n "cd "$PWD" && /usr/bin/yes | sudo dpkg -i *.deb" | xclip -selection clipboard
					yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEST_INSTALOWAC_KERNEL2"
					if [ "$?" = "1" ]; then
					      exit 1
					fi
				fi
			fi
		fi
	#instalacja kerneli ext73
	
	#elif [ "$kern" = "$menu1" ] || [ "$kern" = "$menu1a" ] || [ "$kern" = "$menu2" ] || [ "$kern" = "$menu2a" ] || [ "$kern" = "$menu3" ] || [ "$kern" = "$menu4" ] || [ "$(echo $kern | grep 'Intel C2D, AMD K8')" != "" ] && [ "$blad" != "1" ]; then
	elif [ "$kern" != "" ] && [ "$blad" != "1" ]; then
		if [ "$rodzaj" != "" ]; then
			lista_kerneli
			if [ "$klawisz" = "0" ] && [ "$blad" != "1" ] ; then
				if [ "$(echo $a1)" = "-" ]; then
					rm ./index.html -f; rm $a -rf
					mkdir $a; cd $a
					#wywołanie funkcji pobierania odpowiednich wersji kerneli
					pobieranie_kerneli
					if [ "$(grep $(md5sum linux-image*) $sumy_kontrolne)" != "" ] && [ "$(grep $(md5sum linux-headers*) $sumy_kontrolne)" != "" ]; then
						echo "nie" > /tmp/netext73/ok.txt
						if [ -e linux-headers* ] && [ -e linux-image* ]; then
							if yad --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --height=$((280*$skala)) --width=$((590*$skala)) --text="$TEST_INSTALOWAC_KERNEL3 $rodzaj $TEST_INSTALOWAC_KERNEL4\n\n$(ls *.deb)\n\n$TEXT_INSTALOWAC ?\n\n" ; then
								naglowek > instaluj.sh
								sprawdz_gcc >> instaluj.sh
								instaluj_kernel >> instaluj.sh
								usun_lpt >> instaluj.sh
								instalacja2
								#wywalenie plików po instalacji
								wywal_pobrane_pliki_kernela
								restart
							else
								echo -n "cd $PWD" | xclip -selection clipboard
								yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEST_INSTALOWAC_KERNEL5"
							fi
						else
							dymek  -i $warning1 "$TEXT_UWAGA" "$TEXT_INSTALOWAC_KERNEL6"
							blad=1
						fi
					else
						yad --center --error --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_SUMA_KONTROLNA"
					fi
				else
					yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_INSTALOWAC_KERNEL7"
				fi
			fi
		fi
	fi
