#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język niemiecki: Karolina Franieczek
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#Kontakt

cd /tmp
if [ "$USER" = "root" ]; then
	userek=$(cat /tmp/userek)
	konfiguracja=$(yad --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/mail.png" --text="<span color=\"$kolor_textu\">$TEXT_KONTAKT_Z_AUTORAMI</span>" --form --field "$TEXT_EXT:BTN" --field "$TEXT_NETBIT:BTN" --field "$TEXT_FADEMIND:BTN" --field "$TEXT_ENEDIL:BTN" \
	"su $userek -c \"xdg-open 'http://www.netext73.pl/2014/02/e-x-t-7-3.html'\"" \
	"su $userek -c \"xdg-open 'http://www.netext73.pl/2014/01/netbit73.html'\"" \
	"su $userek -c \"xdg-open 'http://tomaszprzybyl-apel.blogspot.com/'\"" \
	"su $userek -c \"xdg-open 'https://debian-polska.blogspot.com/'\"" \
	--button="gtk-ok:0" --width="300")
else
	yad --icons --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/mail.png" --image-on-top --item-width="200" --read-dir="/opt/NeteXt73/kontakty" \
	--button="gtk-ok:0" --width=450 --height=380  --single-click
	
fi
