#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#instalator microcode i firmware

cd /tmp
rm *.html -f; wget $adres_firmware/index.html 2>&1 | pobieranie2 
if [ -e index.html ]; then
	wersja_firmware=$(cat index.html | grep "href=.*linux" | cut -d '"' -f 2 | cut -d '_' -f 2)
	rm *.html -f
	rm /tmp/*.txt -f; rm /tmp/*.sh -f
	if [ "$(cat /proc/cpuinfo | grep Intel)" != "" ]; then
	      if [ "$(dpkg -l intel-microcode | grep "ii" | awk '{print $1}'| head -n1)" = "ii" ]; then
		    stan_microcode=$TEXT_TAK
	      else
		    stan_microcode="-"
	      fi
	elif [ "$(cat /proc/cpuinfo | grep AMD)" != "" ]; then
	      if [ -e /lib/firmware/amd-ucode/microcode_amd.bin ]; then
		    stan_microcode=$TEXT_TAK
	      else
		    stan_microcode="-"
	      fi
	fi


	#sprawdzenie czy jest nowsza wersja
	if [ "$stan_microcode" != "-" ]; then
	      if [ "$wersja_firmware" != "$(dpkg -l | grep linux-firmware | awk '{print $3}' | head -n 1)" ]; then
	        yad-netext --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --text="$TEXT_MICROCODE2"
		if [ $? = 0 ]; then
		  naglowek > instaluj.sh
		  microcode_inst >> instaluj.sh
		  microcode_firmware  
		fi
	      fi
	fi



	naglowek > instaluj.sh
	if [ "$stan_microcode" != "-" ] && [ "$wersja_firmware" = "$(dpkg -l | grep linux-firmware | awk '{print $3}' | head -n 1)" ]; then
		dymek -i $warning1 "$TEXT_UWAGA" "$TEXT_MICROCODE1"
		#yad-netext --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEXT_MICROCODE1"
		
	elif [ "$stan_microcode" = "-" ]; then
		yad-netext --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --text="$TEXT_MICROCODE2"
		if [ $? = 0 ]; then
		    microcode_inst >> instaluj.sh
		    microcode_firmware
		fi
	fi
fi