#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#monitor

cd /tmp
if [ -e ~/.netext73/monitor ]; then
    if [ "$(cat ~/.netext73/monitor | grep system)" != "" ]; then
	a1=TRUE
    else
	a1=FALSE
    fi
    if [ "$(cat ~/.netext73/monitor | grep powertop)" != "" ]; then
	a2=TRUE
    else
	a2=FALSE
    fi
    if [ "$(cat ~/.netext73/monitor | grep HTOP)" != "" ]; then
	a3=TRUE
    else
	a3=FALSE
    fi
    if [ "$(cat ~/.netext73/monitor | grep saidar)" != "" ]; then
	a4=TRUE
    else
	a4=FALSE
    fi
    if [ "$(cat ~/.netext73/monitor | grep battery)" != "" ]; then
	a5=TRUE
    else
	a5=FALSE
    fi
else

    a1=TRUE
    a2=FALSE
    a3=FALSE
    a4=FALSE
    a5=FALSE
fi

if [ -e /sys/class/power_supply/BAT*/uevent ];then
      konfiguracja=$(yad-netext --center --window-icon="/opt/NeteXt73/ikony/monitor.png" --title="$nazwa_skryptu" --text="<span color=\"$kolor_textu\">$TEXT_MONITOR1</span>" --column="$TEXT_ZAZNACZ" --column="program" --width="355" --height="230" --checklist --list \
      "$a1" "system monitor" \
      "$a2" "powertop" \
      "$a3" "HTOP" \
      "$a4" "saidar" \
      "$a5" "battery" \
      --button="gtk-ok:0" --button="$TEXT_POWROT:1" )
      klawisz=$?
else
      konfiguracja=$(yad-netext --center --window-icon="/opt/NeteXt73/ikony/monitor.png" --title="$nazwa_skryptu" --text="<span color=\"$kolor_textu\">$TEXT_MONITOR1</span>" --column="$TEXT_ZAZNACZ" --column="program" --width="355" --height="230" --checklist --list \
      "$a1" "system monitor" \
      "$a2" "powertop" \
      "$a3" "HTOP" \
      "$a4" "saidar" \
      --button="gtk-ok:0" --button="$TEXT_POWROT:1" )
      klawisz=$?
fi
if [ "$klawisz" = "0" ]; then
    if [ "$klawisz" = "0" ]; then
	echo $konfiguracja > ~/.netext73/monitor
    fi
    if [ "$(echo $konfiguracja | grep system)" != "" ]; then
	    procesor_monitor | x-terminal-emulator -e bash -c "watch -t 'uptime; echo  -n \"\nScaling governor : \"; cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;echo -n \"CPU driver       : \";cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_driver | head -n 1; echo -n \"\nCpu Core Frequency\n\";cat /proc/cpuinfo | grep MHz;echo -n \"\nMemory :\n\";free -m;echo -n \"\nSensors:\n\";sensors'" &
    fi
    if [ "$(echo $konfiguracja | grep powertop)" != "" ]; then
	    x-terminal-emulator -e bash -c "sudo powertop" &
    fi
    if [ "$(echo $konfiguracja | grep HTOP)" != "" ]; then
	    x-terminal-emulator -e bash -c "htop" &
    fi
    if [ "$(echo $konfiguracja | grep saidar)" != "" ]; then
	    x-terminal-emulator -e bash -c "saidar -c" &
    fi
        if [ "$(echo $konfiguracja | grep battery)" != "" ]; then
	    stan_baterii
    fi
fi
