#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

rm -rf /tmp/netext73/sumy/*
mkdir -p /tmp/netext73/sumy
source /opt/NeteXt73/procedury

aktualizacja(){
#odpalanie strony domowej 
if [ ! -e ~/.netext73/strona_domowa ]; then
    xdg-open "http://www.netext73.pl/p/netext73-poczatek.html"
    echo "TRUE" > ~/.netext73/strona_domowa
fi
}

sumy(){
#pobranie sum kontrolnych
    cd /tmp
    wget $adres_sum_kontrolnych 2>&1 | pobieranie && mv sumy.txt $sumy_kontrolne
}

#ostrzeżenie o konfliktach
zaleznosci(){
plik=""
for i in $(echo tlp laptop-mode-tools);do
if [ "$(dpkg -l | awk '{print $2}' | grep $i -x)" != "" ];then
    export plik="$plik $i"
fi
done
if [ "$plik" != "" ]; then
	if yad-netext --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="$TEXT_WARRING_DEP1\n$plik"; then
		naglowek > instaluj.sh
		echo "sudo apt-get purge $plik" >> instaluj.sh
		instalacja
	fi
fi
}

#########################################################################################################################################################################


if [ ! -e /tmp/netext73/userek ]; then
    echo $USER > /tmp/netext73/userek
fi

if [ -e ~/.netext73/root_mode ] && [ "$(cat ~/.netext73/root_mode)" = "TRUE" ]; then
      if [ -e /tmp/netext73/stan_netext ] && [ $(cat /tmp/netext73/stan_netext) = "root" ]; then
	  echo "tryb normalny" > /dev/null
      else
	  cd /opt/NeteXt73 && ./NeteXt73_root ./NeteXt73
	  exit 0
      fi
fi

zaleznosci
sumy &
aktualizacja &


yad-netext --center --icons --class="NeteXt'73" --name="NeteXt'73" --window-icon="/opt/NeteXt73/ikony/netext.png" --image="/opt/NeteXt73/ikony/netext73.png" --image-on-top --item-width="190" --read-dir="/opt/NeteXt73/desktopfiles" --width="830" --height="690" --title="- $nazwa_skryptu -" --button="$TEXT_REBOOT:5" --button="$TEXT_BUG:4" --button="$TEXT_CHANGELOG:3" --button="$TEXT_LICENCJA:2" --button="$TEXT_ZAMKNIJ:1" --single-click
klawisz=$?

if [ "$klawisz" = "2" ]; then
      yad-netext --center --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/logi.png" --on-top --text-info --filename=/opt/NeteXt73/LICENSE --width=600 --height=600 --button="gtk-ok:1" 
      cd /opt/NeteXt73 && ./NeteXt73
elif [ "$klawisz" = "3" ]; then
      yad-netext --center --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/logi.png" --on-top --text-info --filename=/opt/NeteXt73/changelog --width=800 --height=600 --button="gtk-ok:1"
      cd /opt/NeteXt73 && ./NeteXt73
elif [ "$klawisz" = "4" ]; then
      if [ "$USER" = "root" ]; then
	    userek=$(cat /tmp/netext73/userek)
	    su $userek -c "xdg-open \"http://www.netext73.pl/2014/02/netext73-zgaszanie-bedow.html\""
      else
	    xdg-open "http://www.netext73.pl/2014/02/netext73-zgaszanie-bedow.html"
      fi
      cd /opt/NeteXt73 && ./NeteXt73
elif [ "$klawisz" = "5" ]; then
      restart
elif [ "$klawisz" = "1" ]; then
      rm -rf /tmp/netext73
fi

if [ $USER = "root" ] && [ -e /home/root ]; then
    sudo rm -rf /home/root
fi
