#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

rm -rf /tmp/netext73/sumy/*
mkdir -p /tmp/netext73/sumy
source /opt/NeteXt73/procedury

aktualizacja(){
#odpalanie strony domowej 
if [ ! -e ~/.netext73/strona_domowa ]; then
	xdg-open "http://www.netext73.pl/p/netext73-poczatek.html"
	echo "TRUE" > ~/.netext73/strona_domowa
fi
#życzenia świąteczne
DATA=$(date +"%m-%d")
if [ "$DATA" = "12-24" ] ||  [ "$DATA" = "12-25" ] ||  [ "$DATA" = "12-26" ]; then
	yad-netext --center --info --title="$nazwa_skryptu   "  --text="Zespół NeteXt'73 życzy\n<span color=\"$kolor_textu\"><b>Wesołych Świąt Bożego Narodzenia!</b></span>\n\n\nNeteXt'73 team\n<span color=\"$kolor_textu\"><b>wishes Merry Christmas!</b></span>" --window-icon="/opt/NeteXt73/ikony/tux_santa.png" --image="/opt/NeteXt73/ikony/tux_santa.png" --button="gtk-ok:0" --on-top
fi
#życzenia noworoczne
if [ "$DATA" = "12-31" ]; then
	dymek  -i /opt/NeteXt73/ikony/happyny.png "Happy New Year" "<b>NeteXt'73 team wishes Happy New Year $(( $(date +"%Y")+1 ))\nZespół NeteXt'73 życzy Szczęśliwego Nowego Roku $(( $(date +"%Y")+1 ))</b>"
fi
if [ "$DATA" = "01-01" ]; then
	dymek  -i /opt/NeteXt73/ikony/happyny.png "Happy New Year" "<b>NeteXt'73 team wishes Happy New Year $(date +"%Y")\nZespół NeteXt'73 życzy Szczęśliwego Nowego Roku$(date +"%Y")</b>"
fi
}

sumy(){
#pobranie sum kontrolnych i sprawdzanie połączenia z netem
	cd /tmp
	wget $adres_sum_kontrolnych 2>&1 | pobieranie && mv sumy.txt $sumy_kontrolne
	if [ "$(cat $sumy_kontrolne)" = "" ]; then
		yad-netext --center --info --title="$nazwa_skryptu   " --text="<span color=\"$kolor_textu\"><b>$BRAKNETA</b></span>" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --on-top
		exit 1
	else
		KEY="$(echo $RANDOM)"
		#zmienne losowe
		res0=$(mktemp --tmpdir=/tmp/netext73 netext73_0.XXXXXXXX)
		res1=$(mktemp --tmpdir=/tmp/netext73 netext73_1.XXXXXXXX)
		res2=$(mktemp --tmpdir=/tmp/netext73 netext73_2.XXXXXXXX)
		res3=$(mktemp --tmpdir=/tmp/netext73 netext73_3.XXXXXXXX)
		res4=$(mktemp --tmpdir=/tmp/netext73 netext73_4.XXXXXXXX)
		res5=$(mktemp --tmpdir=/tmp/netext73 netext73_5.XXXXXXXX)
		res6=$(mktemp --tmpdir=/tmp/netext73 netext73_6.XXXXXXXX)
		res7=$(mktemp --tmpdir=/tmp/netext73 netext73_7.XXXXXXXX)
		res8=$(mktemp --tmpdir=/tmp/netext73 netext73_8.XXXXXXXX)
		res8=$(mktemp --tmpdir=/tmp/netext73 netext73_9.XXXXXXXX)
		for i in $(cat /tmp/netext73/sumy/sumy_kontrolne.txt | awk '{print $2}' | grep -v -E 'image|amdcccle' -v); do 
			if [ "$(dpkg -l | awk '{print $2}' | grep -x $(echo $i | sed 's/_amd64.deb//'))" = "" ]; then
			      echo "FALSE $i" >> 1.txt
			else
			      echo "TRUE $i" >> 1.txt
			fi
		done	
		sed -i 's/_amd64.deb//g' 1.txt
		sed -i 's/-headers//g' 1.txt
		#zakładki
		yad-netext --plug=$KEY --tabnum=1 --checklist --list $(cat 1.txt | grep fglrx_     | sort -r) --column "$TEXT_ZNITY1" --column "catalist" &> $res0 &
		yad-netext --plug=$KEY --tabnum=2 --checklist --list $(cat 1.txt | grep nvidia     | grep -v -E "nvidia-settings.*|libnvidia-"| sort -r) --column "$TEXT_ZNITY1" --column "nvidia" &> $res1 &
		yad-netext --plug=$KEY --tabnum=3 --checklist --list $(cat 1.txt | grep k8 	   | sort -r) --column "$TEXT_ZNITY1" --column "kernel k8" &> $res2 &
		yad-netext --plug=$KEY --tabnum=4 --checklist --list $(cat 1.txt | grep atom	   | sort -r) --column "$TEXT_ZNITY1" --column "kernel atom" &> $res3 &
		yad-netext --plug=$KEY --tabnum=5 --checklist --list $(cat 1.txt | grep i7 	   | egrep -v pro | sort -r) --column "$TEXT_ZNITY1" --column "kernel i7" &> $res4 &
		yad-netext --plug=$KEY --tabnum=6 --checklist --list $(cat 1.txt | grep i7-pro     | sort -r) --column "$TEXT_ZNITY1" --column "kernel i7-pro" &> $res5 &
		yad-netext --plug=$KEY --tabnum=7 --checklist --list $(cat 1.txt | grep brazos     | egrep -v pro | sort -r) --column "$TEXT_ZNITY1" --column "kernel brazos" &> $res6 &
		yad-netext --plug=$KEY --tabnum=8 --checklist --list $(cat 1.txt | grep brazos-pro | sort -r) --column "$TEXT_ZNITY1" --column "kernel brazos-pro" &> $res7 &

		yad-netext --notebook --key=$KEY --on-top --title=" $nazwa_skryptu   " --width=570 --height=300 --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" \
		--tab="catalyst" --tab="nvidia" --tab="k8" --tab="atom" --tab="i7" --tab="i7-pro" --tab="brazos" --tab="brazos-pro" --button="gtk-ok:0" --text="lista udostępnianych plików wraz ze statusem instalacji:"
		rm 1.txt -f
	fi
}

#ostrzeżenie o konfliktach
zaleznosci(){
cd /tmp/netext73
plik=""
for i in $(echo tlp acpi-call laptop-mode-tools ulatelcy ulatencyd cpufrequtils);do
if [ "$(dpkg -l | awk '{print $2}' | grep $i -x)" != "" ];then
	export plik="$plik $i"
fi
done
if [ "$plik" != "" ]; then
	if yad-netext --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="$TEXT_WARRING_DEP1\n$plik"; then
		naglowek > instaluj.sh
		echo "sudo apt-get purge $plik" >> instaluj.sh
		echo "sudo apt-get autoremove" >> instaluj.sh
		instalacja
	fi
fi
}

#########################################################################################################################################################################


if [ ! -e /tmp/netext73/userek ]; then
	echo $USER > /tmp/netext73/userek
fi

if [ -e ~/.netext73/root_mode ] && [ "$(cat ~/.netext73/root_mode)" = "TRUE" ]; then
	if [ -e /tmp/netext73/stan_netext ] && [ $(cat /tmp/netext73/stan_netext) = "root" ]; then
	      sudo -K
	else
	      cd /opt/NeteXt73 && ./NeteXt73_root ./NeteXt73
	      exit 0
	fi
fi
export userek=$(cat /tmp/netext73/userek)
zaleznosci
sumy &
aktualizacja &

if [ -e ~/.netext73/kernel_premium ] && [ -e ~/.netext73/vsftpd/vsftpd ] && [ -e ~/.netext73/has* ]; then
	yad-netext --center --icons --class="NeteXt'73" --name="NeteXt'73" --window-icon="/opt/NeteXt73/ikony/netext.png" --image="/opt/NeteXt73/ikony/netext73.png" --image-on-top --item-width="190" --read-dir="/opt/NeteXt73/desktopfiles" --width="830" --height="690" --title="- $nazwa_skryptu -" --button="vsFTPd:3" --button="$TEXT_REBOOT:2" --button="$TEXT_ZAMKNIJ:1" --single-click
	klawisz=$?
else
	yad-netext --center --icons --class="NeteXt'73" --name="NeteXt'73" --window-icon="/opt/NeteXt73/ikony/netext.png" --image="/opt/NeteXt73/ikony/netext73.png" --image-on-top --item-width="190" --read-dir="/opt/NeteXt73/desktopfiles" --width="830" --height="690" --title="- $nazwa_skryptu -" --button="$TEXT_REBOOT:2" --button="$TEXT_ZAMKNIJ:1" --single-click
	klawisz=$?
fi

if [ "$klawisz" = "2" ]; then
	restart
elif [ "$klawisz" = "1" ]; then
	rm -rf /tmp/netext73
elif  [ "$klawisz" = "3" ] ; then    
	chmod a+x ~/.netext73/vsftpd/vsftpd
	~/.netext73/vsftpd/./vsftpd
fi

if [ $USER = "root" ] && [ -e /home/root ]; then
	sudo rm -rf /home/root
fi