#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#start
cd /opt/NeteXt73/
source /opt/NeteXt73/procedury
if [ "$1" = "kontakty" ]; then
	#przygotowanie informacji o zainstalowanych plikach
	rm /tmp/netext73/sumy/pliki.txt -f
	dpkg -l | grep -wE "linux-headers|nvidia|fglrx" | grep ii > /tmp/netext73/sumy/pakiety.txt
	cat /tmp/netext73/sumy/pakiety.txt | grep linux-headers		| awk '{print $2}'  	> /tmp/netext73/sumy/lista.txt
	cat /tmp/netext73/sumy/pakiety.txt | grep nvidia 	  	| awk '{print $2"_"$3}' >> /tmp/netext73/sumy/lista.txt
	cat /tmp/netext73/sumy/pakiety.txt | awk '{print $2"_"$3}' 	| sed 's/.://g' | grep fglrx_ >> /tmp/netext73/sumy/lista.txt
	cat /tmp/netext73/sumy/sumy_kontrolne.txt | awk '{print $2}' 	| grep -v -E 'image|amdcccle' -v | sed 's/_amd64.deb//g' > /tmp/netext73/sumy/pakiety.txt
	
	for i in $(cat /tmp/netext73/sumy/pakiety.txt); do 
		if [ "$(echo $i | grep fglrx )" = "" ];then
			if [ "$(cat /tmp/netext73/sumy/lista.txt | grep -x $i)" = "" ]; then
				echo "FALSE $i" >> /tmp/netext73/sumy/pliki.txt
			else
				echo "TRUE $i" >> /tmp/netext73/sumy/pliki.txt
			fi
		else
			if [ "$(cat /tmp/netext73/sumy/lista.txt | grep -x $(echo $i | sed 's/.*_fglrx/fglrx/g'))" = "" ]; then
				echo "FALSE $i" >> /tmp/netext73/sumy/pliki.txt
			else
				echo "TRUE $i" >> /tmp/netext73/sumy/pliki.txt
			fi
		fi
	done
	rm -f /tmp/netext73/sumy/pakiety.txt 
	sed -i 's/_amd64.deb//g' /tmp/netext73/sumy/pliki.txt
	sed -i 's/-headers//g' /tmp/netext73/sumy/pliki.txt
	cat /tmp/netext73/sumy/pliki.txt | sort -r | uniq > /tmp/netext73/sumy/pakiety.txt
	rm -f /tmp/netext73/sumy/pliki.txt
	KEY="$(echo $RANDOM)"

	#zmienne losowe
	res1=$(mktemp --tmpdir=/tmp/netext73 netext73_1.XXXXXXXX)
	res2=$(mktemp --tmpdir=/tmp/netext73 netext73_2.XXXXXXXX)
	res3=$(mktemp --tmpdir=/tmp/netext73 netext73_3.XXXXXXXX)
	res4=$(mktemp --tmpdir=/tmp/netext73 netext73_4.XXXXXXXX)
	res5=$(mktemp --tmpdir=/tmp/netext73 netext73_5.XXXXXXXX)
	res6=$(mktemp --tmpdir=/tmp/netext73 netext73_6.XXXXXXXX)
	res7=$(mktemp --tmpdir=/tmp/netext73 netext73_7.XXXXXXXX)
	res8=$(mktemp --tmpdir=/tmp/netext73 netext73_8.XXXXXXXX)
	res9=$(mktemp --tmpdir=/tmp/netext73 netext73_9.XXXXXXXX)
	res10=$(mktemp --tmpdir=/tmp/netext73 netext73_10.XXXXXXXX)
	res11=$(mktemp --tmpdir=/tmp/netext73 netext73_11.XXXXXXXX)
	res12=$(mktemp --tmpdir=/tmp/netext73 netext73_12.XXXXXXXX)
	res13=$(mktemp --tmpdir=/tmp/netext73 netext73_13.XXXXXXXX)
	res14=$(mktemp --tmpdir=/tmp/netext73 netext73_14.XXXXXXXX)
	yad --plug=$KEY --tabnum=1 --icons --image-on-top --single-click --item-width=$((200*$skala)) --read-dir=/opt/NeteXt73/kontakty &> $res1 &
	yad --plug=$KEY --tabnum=2 --text-info --filename=/opt/NeteXt73/changelog &> $res2 &
	yad --plug=$KEY --tabnum=3 --text-info --filename=/opt/NeteXt73/LICENSE &> $res3 &
	yad --plug=$KEY --tabnum=4 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep fglrx_ ) --column "$TEXT_ZNITY1" --column "catalist" &> $res4 &
	yad --plug=$KEY --tabnum=5 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep nvidia | grep -v -E "nvidia-settings.*|libnvidia-") --column "$TEXT_ZNITY1" --column "nvidia" &> $res5 &
	yad --plug=$KEY --tabnum=6 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep k8 	  ) --column "$TEXT_ZNITY1" --column "kernel k8" &> $res6 &
	yad --plug=$KEY --tabnum=7 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep atom	  ) --column "$TEXT_ZNITY1" --column "kernel atom" &> $res7 &
	yad --plug=$KEY --tabnum=8 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt | grep sandy) --column "$TEXT_ZNITY1" --column "kernel sandy" &> $res8 &
	yad --plug=$KEY --tabnum=9 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt | grep ivy) --column "$TEXT_ZNITY1" --column "kernel ivy" &> $res9 &
	yad --plug=$KEY --tabnum=10 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt | grep haswell) --column "$TEXT_ZNITY1" --column "kernel haswell" &> $res10 &
	yad --plug=$KEY --tabnum=11 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt | grep broadwell) --column "$TEXT_ZNITY1" --column "kernel broadwell" &> $res11 &
	yad --plug=$KEY --tabnum=12 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt | grep brazos | egrep -v pro ) --column "$TEXT_ZNITY1" --column "kernel brazos" &> $res12 &
	yad --plug=$KEY --tabnum=13 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt | grep bulldozer) --column "$TEXT_ZNITY1" --column "kernel bulldozer" &> $res13 &
	yad --plug=$KEY --tabnum=14 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt | grep piledriver) --column "$TEXT_ZNITY1" --column "kernel piledriver" &> $res14 &
	
	yad --notebook --key=$KEY --center --title="$nazwa_skryptu1 " --tab="$TEXT_KONTAKT_Z_AUTORAMI" --tab="$TEXT_CHANGELOG" --tab="$TEXT_LICENCJA" \
	--tab="catalyst" --tab="nvidia" --tab="k8" --tab="atom" \
	--tab="sandy" --tab="ivy" --tab="haswell" --tab="broadwell" \
	--tab="brazos" --tab="buldozer" --tab="piledriver" \
	--window-icon="/opt/NeteXt73/ikony/netext.png" --on-top --width=$((860*$skala)) --height=$((350*$skala)) --button="$TEXT_ZAMKNIJ:1" --button="$TEXT_BUG:2"
	klawisz=$?
	rm /tmp/netext73/sumy/pliki.txt $res1 $res2 $res3 $res4 $res5 $res6 $res7 $res8 $res9 $res10 $res11 $res12 $res13 $res14 -f
	if [ "$klawisz" = "2" ]; then
		xdg-open "http://www.netext73.pl/2014/02/netext73-zgaszanie-bedow.html"
	fi
else
	if [ -e ~/.netext73/root_mode ] && [ "$(cat ~/.netext73/root_mode)" = "TRUE" ] && [ -e /tmp/netext73/stan_netext ] && [ "$(cat /tmp/netext73/stan_netext)" = "root" ] && [ "$(echo $1 | grep 'NeteXt73')" = "" ]; then
		sudo -S $1
	else
		echo "root" > /tmp/netext73/stan_netext
		while ! yad --center --on-top --title="$nazwa_skryptu1" --entry --hide-text --window-icon="/opt/NeteXt73/ikony/key.png" --image="/opt/NeteXt73/ikony/key.png" --text="NeteXt'73\n\nRoot-mode\n\n$TEXT_PASSWD1" --button="gtk-ok:0" | sudo -S $1; do
			if $(yad --center --question --title="$nazwa_skryptu1" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_NIE:1" --text="$TEXT_PASSWD"); then
				exit 0
			fi
		done

	fi
fi
sudo -K
