#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders.ubf.pl@gmail.com
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#instalator sterowników do grafik Radeon

cd /tmp
rm *.txt -f; rm *.sh -f; rm *.html -f
if [ "$(lspci | grep VGA | awk '{print tolower($0)}' | grep radeon)" = "" ]; then
    notify-send -i $warning1 "$TEXT_UWAGA" "$TEXT_STEROWNIKI3"
else
    if  [ "$bit2" = "i386" ]; then
	    notify-send -i $warning1 "$TEXT_UWAGA" "$TEXT_STEROWNIKI1"
    elif [ "$bit2" = "amd64" ]; then
	    wget $adres_sterownikow/index.html  2>&1 | pobieranie2 
	    if [ -e index.html ]; then
		    cat index.html | grep "href=" ./index.html   | cut -d '"' -f 2 | grep 'fglrx_' | grep $bit2 | sed 's/.deb//' >> 1a.txt
		    cat 1a.txt | sort -r > 2a.txt
		    lista=$(cat 2a.txt | tr '\n' '!' | sed -e '$s/!$//g' )
		    rm *.txt -f
		    petla_duza="tak"
		    while [ $petla_duza = "tak" ]; do
		    ster=$(yad-netext --title="$nazwa_skryptu" --width=410 --window-icon="/opt/NeteXt73/ikony/radeon.png" --text="$TEXT_STEROWNIKI2 <span color=\"$kolor_textu\"><b>Radeon</b></span>" --form --field="$TEXT_STEROWNIK:CB" "$lista" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
			    klawisz=$?; ster=$(echo $ster | cut -d "|" -f 1)
			    if [ "$ster" != "" ] && [ "$klawisz" = "0" ]; then
			      rm *.deb -f
			      wget $adres_sterownikow/1.txt 2>&1 | pobieranie 
			      
				      a=$ster.deb; a1=$a
				      dziala=0; MB1=$(echo "scale=2;$(wget --server-response --spider $adres_sterownikow/$a 2>&1 | grep "ontent.*ength" | awk '{print $2}')/1024/1024"|bc); MB="- $MB1 MB"
				      wget $adres_sterownikow/$a 2>&1 | pobieranie 
					    a=$(echo $ster.deb | sed "s/fglrx/fglrx-amdcccle/")
					    dziala=0; MB1=$(echo "scale=2;$(wget --server-response --spider $adres_sterownikow/$a 2>&1 | grep "ontent.*ength" | awk '{print $2}')/1024/1024"|bc); MB="- $MB1 MB"
					    wget $adres_sterownikow/$a 2>&1 | pobieranie 
				      if [ -e $a* ] && [ -e $a1* ] && [ "$(grep $(md5sum $a) 1.txt)" != "" ] && [ "$(grep $(md5sum $a1) 1.txt)" != "" ]; then
					      echo "nie" > /tmp/ok.txt
					      zamknij_program
					      naglowek > instaluj.sh
					      radeon >> instaluj.sh
					      instalacja
				      else
					      yad-netext --error --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_SUMA_KONTROLNA"
				      fi
			    elif [ "$klawisz" = "1" ]; then
				  petla_duza="nie"
				  rm ./index.html *txt -f
			    fi
			    done
	    fi
    fi
fi