#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

backdoor(){

#
# A simple check to see if running ssh processes contain any string that have
# been designated an indication of Fokirtor by Symantec.
#
# More info here:
# http://www.symantec.com/connect/blogs/linux-back-door-uses-covert-communication-protocol
#
# (c) 2013, Kumina bv, info@kumina.nl
#
# You are free to use, modify and distribute this check in any way you see
# fit. Just don't say you wrote it.
#
# This check is created for Debian Squeeze/Wheezy, no idea if it'll work in
# other distros. You'll need gdb-minimal (for gcore) installed.

# We need to be root


# For all pids of the ssh process, do the check

echo "for pid in \`/bin/pidof sshd\`; do"
echo "        t=\$(/bin/mktemp)"
echo "        /usr/bin/gdb </dev/null --nx --batch \ "
echo "          -ex \"set pagination off\" -ex \"set height 0 \" -ex \"set width 0\" \ "
echo "          -ex \"attach \$pid\" -ex \"gcore \$t\" -ex detach -ex quit"
echo "        i=0"
echo "        for str in hbt= key= dhost= sp= sk= dip=; do"
echo "                /usr/bin/strings \$t | /bin/grep \"\${str}[[:digit:]]\""
echo "                if [ \$? -eq 0 ]; then"
echo "                        i=\$((\$i + 1))"
echo "                fi"
echo "        done"
echo "        /bin/rm \$t"
echo "        if [ \$i -eq 6 ]; then"
echo "                echo \"\n$TEXT_BACK_CRITIC \${pid}!\""
echo "		      exit"
echo "        fi"
echo "done"

echo "echo \"\n$TEXT_BACK_OK\""
echo "exit"
}

#########################################################################################################################################################################
#Skrypty


cd /tmp

if [ "$(cat /etc/sysctl.conf | grep 'net.ipv6.conf.all.disable_ipv6 = 1')" = "" ]; then
	menu="$MENU3!$MENU4!$MENU5!$MENU6!$MENU7!$MENU9!$MENU10!$MENU11!$MENU12"
    else
	menu="$MENU3!$MENU4!$MENU5!$MENU6!$MENU8!$MENU9!$MENU10!$MENU11!$MENU12"
fi

skrypt=$(yad-netext --center --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/skrypty.png" --form --field="$TEXT_SKRYPT1:CB" "$menu" --button="gtk-ok:0" --button="$TEXT_POWROT:1"  )
klawisz=$?; skrypt=$(echo $skrypt | cut -d "|" -f 1)
if [ $klawisz = 0 ]; then 
	
	#kasujem dane po konfigach
	if [ "$skrypt" = "$MENU3" ]; then
	    if [ "$(dpkg -l | grep '^rc' | awk '{print $2}' | head -n1)" != "" ]; then 
		  xterm -T configi -e bash -c "echo \"$TEXT_INSTALACJA1\"; sudo dpkg -l | grep '^rc' | awk '{print \$2}' | xargs sudo dpkg --purge; echo -e \"$TEXT_INSTALACJA2\" ;read ent"
	    else 
		  yad-netext --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEXT_CONFIG1" 
	    fi
	#zabijamy procesy zombie
	elif [ "$skrypt" = "$MENU4" ]; then
	    
	    ps axo stat,ppid,pid,comm | grep -w defunct > procesy.txt
	      
	    if [ "$(cat procesy.txt)" = "" ]; then
		  yad-netext --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEXT_ZOMBIE2"
	    else
		  sed -i 1d procesy.txt
		  sed -i '/^[^#]/s:^:FALSE :' procesy.txt
		  a=$(yad-netext --center --height=540 --width=440 --window-icon="/opt/NeteXt73/ikony/skrypty.png" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --title="$nazwa_skryptu" --text="$TEXT_ZOMBIE1" --column="" --column="STAT" --column="PPID" --column="PID" --column="COMMAND" --checklist --list $(cat procesy.txt))
		  echo $a > zabij
		  sed -i 's/TRUE/\n/g' zabij; sed -i '/^\ *$/d' zabij
		  for i in $(cat zabij  | cut -d '|' -f 3)
		  do
		      sudo kill $i
		  done
	    fi
	    rm *.txt -f
	#odpalamy tasksel
	elif [ "$skrypt" = "$MENU5" ]; then
	    cd /tmp
	    x-terminal-emulator -e bash -c "echo -e \"$TEXT_TASKSEL1\"; sudo tasksel; echo -e \"$TEXT_INSTALACJA2\"; read ent"
	#synchronizuj czas z internetu
	elif [ "$skrypt" = "$MENU6" ]; then    
	    xterm -T time -e bash -c "echo \"$TEXT_INSTALACJA1\"; sudo ntpdate tempus1.gum.gov.pl; echo -e \"$TEXT_INSTALACJA2\" ;read ent"
	
	#ipv6 off
	elif [ "$skrypt" = "$MENU7" ]; then  
	    naglowek > instaluj.sh
	    ipv6_off >> instaluj.sh
	    instalacja
	#ipv6 on
	elif [ "$skrypt" = "$MENU8" ]; then  
	    naglowek > instaluj.sh
	    ipv6_on >> instaluj.sh
	    instalacja	
	#backdoor SSHD
	elif [ "$skrypt" = "$MENU9" ]; then  
	    naglowek > instaluj.sh
	    backdoor >> instaluj.sh
	    instalacja3
	elif [ "$skrypt" = "$MENU10" ]; then  
	    naglowek > instaluj.sh
	    echo "sudo mv /usr/bin/google-chrome-stable /usr/bin/google-chrome" >> instaluj.sh
	    echo "sudo sed -i 's/google-chrome-stable/google-chrome/' /usr/share/applications/google-chrome.desktop" >> instaluj.sh
	    instalacja3
	elif [ "$skrypt" = "$MENU11" ]; then  
	    naglowek > instaluj.sh 
	    echo "sudo mv /lib/udev/rules.d/40-usb_modeswitch.rules /lib/udev/rules.d/61-usb_modeswitch.rules" >> instaluj.sh
	    instalacja3
	elif [ "$skrypt" = "$MENU12" ]; then    
	    /opt/NeteXt73/./gosc
	fi
	
fi
	
	
	
	
	