#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## opiekun repozytorium eloaders eloaders@linux.pl
## tłumaczenie na język angielski: Tomasz Przybył (FadeMind)
## tłumaczenie na język francuski: Michał Radwański (enedil)
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury


#########################################################################################################################################################################
#Skrypty


cd /tmp/netext73

if [ "$(cat /etc/sysctl.conf | grep 'net.ipv6.conf.all.disable_ipv6 = 1')" = "" ]; then
	menu="$MENU3!$MENU4!$MENU5!$MENU6!$MENU7!$MENU10!$MENU11!BurnTest"
    else
	menu="$MENU3!$MENU4!$MENU5!$MENU6!$MENU8!$MENU10!$MENU11!BurnTest"
fi

skrypt=$(yad-netext --center --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/skrypty.png" --image="/opt/NeteXt73/ikony/skrypty.png" --form --field="$TEXT_SKRYPT1:CB" "$menu" --button="gtk-ok:0" --button="$TEXT_POWROT:1"  )
klawisz=$?; skrypt=$(echo $skrypt | cut -d "|" -f 1)
if [ $klawisz = 0 ]; then
	#kasujem dane po konfigach
	if [ "$skrypt" = "$MENU3" ]; then
	    if [ "$(dpkg -l | grep '^rc' | awk '{print $2}' | head -n1)" != "" ]; then
		  xterm -T configi -e bash -c "echo \"$TEXT_INSTALACJA1\"; sudo dpkg -l | grep '^rc' | awk '{print \$2}' | xargs sudo dpkg --purge; echo -e \"$TEXT_INSTALACJA2\" ;read ent"
	    else 
		  yad-netext --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEXT_CONFIG1" 
	    fi
	#zabijamy procesy zombie
	elif [ "$skrypt" = "$MENU4" ]; then
	    ps axo stat,ppid,pid,comm | grep -w defunct > procesy.txt
	    if [ "$(cat procesy.txt)" = "" ]; then
		  yad-netext --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEXT_ZOMBIE2"
	    else
		  sed -i 1d procesy.txt
		  sed -i '/^[^#]/s:^:FALSE :' procesy.txt
		  a=$(yad-netext --center --height=540 --width=440 --window-icon="/opt/NeteXt73/ikony/skrypty.png" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --title="$nazwa_skryptu" --text="$TEXT_ZOMBIE1" --column="" --column="STAT" --column="PPID" --column="PID" --column="COMMAND" --checklist --list $(cat procesy.txt))
		  echo $a > zabij
		  sed -i 's/TRUE/\n/g' zabij; sed -i '/^\ *$/d' zabij
		  for i in $(cat zabij  | cut -d '|' -f 3)
		  do
		      sudo kill $i
		  done
	    fi
	    rm *.txt -f
	#odpalamy tasksel
	elif [ "$skrypt" = "$MENU5" ]; then
	    cd /tmp/netext73
	    x-terminal-emulator -e bash -c "echo -e \"$TEXT_TASKSEL1\"; sudo tasksel; echo -e \"$TEXT_INSTALACJA2\"; read ent"
	#synchronizuj czas z internetu
	elif [ "$skrypt" = "$MENU6" ]; then
	    xterm -T time -e bash -c "echo \"$TEXT_INSTALACJA1\"; sudo ntpdate tempus1.gum.gov.pl; echo -e \"$TEXT_INSTALACJA2\" ;read ent"
	#ipv6 off
	elif [ "$skrypt" = "$MENU7" ]; then
	    naglowek > instaluj.sh
	    ipv6_off >> instaluj.sh
	    instalacja
	#ipv6 on
	elif [ "$skrypt" = "$MENU8" ]; then
	    naglowek > instaluj.sh
	    ipv6_on >> instaluj.sh
	    instalacja
	#chrome gtk fix
	elif [ "$skrypt" = "$MENU10" ]; then
	    naglowek > instaluj.sh
	    echo "sudo mv /usr/bin/google-chrome-stable /usr/bin/google-chrome" >> instaluj.sh
	    echo "sudo sed -i 's/google-chrome-stable/google-chrome/' /usr/share/applications/google-chrome.desktop" >> instaluj.sh
	    instalacja3
	#modem usb fix
	elif [ "$skrypt" = "$MENU11" ]; then
	    naglowek > instaluj.sh
	    echo "sudo mv /lib/udev/rules.d/40-usb_modeswitch.rules /lib/udev/rules.d/61-usb_modeswitch.rules" >> instaluj.sh
	    instalacja3
	elif [ "$skrypt" = "BurnTest" ]; then
	burntest
	fi
fi

