#!/bin/bash
LATEST_VERSION=`grep 'v[0-9]' ./changelog | awk '/./{line=$0} END{print line}' | cut -d 'v' -f 2`
PKG_NAME="netext73"
#tekst=$(sed -n -e "/$LATEST_VERSION/,/koniec/p" changelog)
dch --controlmaint --distribution stable -v $LATEST_VERSION --package netext73
